/* This file was automatically generated by CasADi 3.6.3.
 *  It consists of: 
 *   1) content generated by CasADi runtime: not copyrighted
 *   2) template code copied from CasADi source: permissively licensed (MIT-0)
 *   3) user code: owned by the user
 *
 */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) Path_parametric_MPC_expl_vde_adj_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int int
#endif

/* Add prefix to internal symbols */
#define casadi_c0 CASADI_PREFIX(c0)
#define casadi_c1 CASADI_PREFIX(c1)
#define casadi_c2 CASADI_PREFIX(c2)
#define casadi_c3 CASADI_PREFIX(c3)
#define casadi_clear CASADI_PREFIX(clear)
#define casadi_clear_casadi_int CASADI_PREFIX(clear_casadi_int)
#define casadi_copy CASADI_PREFIX(copy)
#define casadi_de_boor CASADI_PREFIX(de_boor)
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_f1 CASADI_PREFIX(f1)
#define casadi_f2 CASADI_PREFIX(f2)
#define casadi_f3 CASADI_PREFIX(f3)
#define casadi_f4 CASADI_PREFIX(f4)
#define casadi_fill CASADI_PREFIX(fill)
#define casadi_fill_casadi_int CASADI_PREFIX(fill_casadi_int)
#define casadi_fmax CASADI_PREFIX(fmax)
#define casadi_low CASADI_PREFIX(low)
#define casadi_nd_boor_eval CASADI_PREFIX(nd_boor_eval)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_s2 CASADI_PREFIX(s2)
#define casadi_s3 CASADI_PREFIX(s3)
#define casadi_s4 CASADI_PREFIX(s4)
#define casadi_s5 CASADI_PREFIX(s5)
#define casadi_s6 CASADI_PREFIX(s6)
#define casadi_s7 CASADI_PREFIX(s7)
#define casadi_s8 CASADI_PREFIX(s8)
#define casadi_s9 CASADI_PREFIX(s9)
#define casadi_sq CASADI_PREFIX(sq)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

void casadi_de_boor(casadi_real x, const casadi_real* knots, casadi_int n_knots, casadi_int degree, casadi_real* boor) {
  casadi_int d, i;
  for (d=1;d<degree+1;++d) {
    for (i=0;i<n_knots-d-1;++i) {
      casadi_real b, bottom;
      b = 0;
      bottom = knots[i + d] - knots[i];
      if (bottom) b = (x - knots[i]) * boor[i] / bottom;
      bottom = knots[i + d + 1] - knots[i + 1];
      if (bottom) b += (knots[i + d + 1] - x) * boor[i + 1] / bottom;
      boor[i] = b;
    }
  }
}

void casadi_fill(casadi_real* x, casadi_int n, casadi_real alpha) {
  casadi_int i;
  if (x) {
    for (i=0; i<n; ++i) *x++ = alpha;
  }
}

void casadi_fill_casadi_int(casadi_int* x, casadi_int n, casadi_int alpha) {
  casadi_int i;
  if (x) {
    for (i=0; i<n; ++i) *x++ = alpha;
  }
}

void casadi_clear(casadi_real* x, casadi_int n) {
  casadi_int i;
  if (x) {
    for (i=0; i<n; ++i) *x++ = 0;
  }
}

void casadi_clear_casadi_int(casadi_int* x, casadi_int n) {
  casadi_int i;
  if (x) {
    for (i=0; i<n; ++i) *x++ = 0;
  }
}

casadi_int casadi_low(casadi_real x, const casadi_real* grid, casadi_int ng, casadi_int lookup_mode) {
  switch (lookup_mode) {
    case 1:
      {
        casadi_real g0, dg;
        casadi_int ret;
        g0 = grid[0];
        dg = grid[ng-1]-g0;
        ret = (casadi_int) ((x-g0)*(ng-1)/dg);
        if (ret<0) ret=0;
        if (ret>ng-2) ret=ng-2;
        return ret;
      }
    case 2:
      {
        casadi_int start, stop, pivot;
        if (ng<2 || x<grid[1]) return 0;
        if (x>grid[ng-1]) return ng-2;
        start = 0;
        stop  = ng-1;
        while (1) {
          pivot = (stop+start)/2;
          if (x < grid[pivot]) {
            if (pivot==stop) return pivot;
            stop = pivot;
          } else {
            if (pivot==start) return pivot;
            start = pivot;
          }
        }
      }
    default:
      {
        casadi_int i;
        for (i=0; i<ng-2; ++i) {
          if (x < grid[i+1]) break;
        }
        return i;
      }
  }
}

void casadi_nd_boor_eval(casadi_real* ret, casadi_int n_dims, const casadi_real* all_knots, const casadi_int* offset, const casadi_int* all_degree, const casadi_int* strides, const casadi_real* c, casadi_int m, const casadi_real* all_x, const casadi_int* lookup_mode, casadi_int* iw, casadi_real* w) {
  casadi_int n_iter, k, i, pivot;
  casadi_int *boor_offset, *starts, *index, *coeff_offset;
  casadi_real *cumprod, *all_boor;
  boor_offset = iw; iw+=n_dims+1;
  starts = iw; iw+=n_dims;
  index = iw; iw+=n_dims;
  coeff_offset = iw;
  cumprod = w; w+= n_dims+1;
  all_boor = w;
  boor_offset[0] = 0;
  cumprod[n_dims] = 1;
  coeff_offset[n_dims] = 0;
  n_iter = 1;
  for (k=0;k<n_dims;++k) {
    casadi_real *boor;
    const casadi_real* knots;
    casadi_real x;
    casadi_int degree, n_knots, n_b, L, start;
    boor = all_boor+boor_offset[k];
    degree = all_degree[k];
    knots = all_knots + offset[k];
    n_knots = offset[k+1]-offset[k];
    n_b = n_knots-degree-1;
    x = all_x[k];
    L = casadi_low(x, knots+degree, n_knots-2*degree, lookup_mode[k]);
    start = L;
    if (start>n_b-degree-1) start = n_b-degree-1;
    starts[k] = start;
    casadi_clear(boor, 2*degree+1);
    if (x>=knots[0] && x<=knots[n_knots-1]) {
      if (x==knots[1]) {
        casadi_fill(boor, degree+1, 1.0);
      } else if (x==knots[n_knots-1]) {
        boor[degree] = 1;
      } else if (knots[L+degree]==x) {
        boor[degree-1] = 1;
      } else {
        boor[degree] = 1;
      }
    }
    casadi_de_boor(x, knots+start, 2*degree+2, degree, boor);
    boor+= degree+1;
    n_iter*= degree+1;
    boor_offset[k+1] = boor_offset[k] + degree+1;
  }
  casadi_clear_casadi_int(index, n_dims);
  for (pivot=n_dims-1;pivot>=0;--pivot) {
    cumprod[pivot] = (*(all_boor+boor_offset[pivot]))*cumprod[pivot+1];
    coeff_offset[pivot] = starts[pivot]*strides[pivot]+coeff_offset[pivot+1];
  }
  for (k=0;k<n_iter;++k) {
    casadi_int pivot = 0;
    for (i=0;i<m;++i) ret[i] += c[coeff_offset[0]+i]*cumprod[0];
    index[0]++;
    {
      while (index[pivot]==boor_offset[pivot+1]-boor_offset[pivot]) {
        index[pivot] = 0;
        if (pivot==n_dims-1) break;
        index[++pivot]++;
      }
      while (pivot>0) {
        cumprod[pivot] = (*(all_boor+boor_offset[pivot]+index[pivot]))*cumprod[pivot+1];
        coeff_offset[pivot] = (starts[pivot]+index[pivot])*strides[pivot]+coeff_offset[pivot+1];
        pivot--;
      }
    }
    cumprod[0] = (*(all_boor+index[0]))*cumprod[1];
    coeff_offset[0] = (starts[0]+index[0])*m+coeff_offset[1];
  }
}

void casadi_copy(const casadi_real* x, casadi_int n, casadi_real* y) {
  casadi_int i;
  if (y) {
    if (x) {
      for (i=0; i<n; ++i) *y++ = *x++;
    } else {
      for (i=0; i<n; ++i) *y++ = 0.;
    }
  }
}

casadi_real casadi_fmax(casadi_real x, casadi_real y) {
/* Pre-c99 compatibility */
#if __STDC_VERSION__ < 199901L
  return x>y ? x : y;
#else
  return fmax(x, y);
#endif
}

casadi_real casadi_sq(casadi_real x) { return x*x;}

static const casadi_int casadi_s0[2] = {0, 18};
static const casadi_int casadi_s1[1] = {2};
static const casadi_int casadi_s2[1] = {1};
static const casadi_int casadi_s3[1] = {0};
static const casadi_int casadi_s4[2] = {0, 20};
static const casadi_int casadi_s5[1] = {3};
static const casadi_int casadi_s6[12] = {8, 1, 0, 8, 0, 1, 2, 3, 4, 5, 6, 7};
static const casadi_int casadi_s7[5] = {1, 1, 0, 1, 0};
static const casadi_int casadi_s8[10] = {6, 1, 0, 6, 0, 1, 2, 3, 4, 5};
static const casadi_int casadi_s9[11] = {9, 1, 0, 7, 2, 3, 4, 5, 6, 7, 8};

static const casadi_real casadi_c0[18] = {0., 0., 0., 2.2222222222222223e+00, 3.3333333333333330e+00, 4.4444444444444446e+00, 6.1111111111111107e+00, 7.7777777777777777e+00, 9.4444444444444446e+00, 1.1666666666666666e+01, 1.3333333333333332e+01, 1.6111111111111111e+01, 1.9444444444444443e+01, 25., 3.3333333333333336e+01, 5.5555555555555557e+01, 5.5555555555555557e+01, 5.5555555555555557e+01};
static const casadi_real casadi_c1[15] = {-9.0709769613017976e-01, 2.1669539226035911e-01, 1.6005759674551534e-02, 5.6178113236704741e-02, 2.2557705914110521e-02, 2.6866981642334448e-02, 4.9974367516551946e-02, -6.2887588246058140e-02, 1.5441029428313660e-01, 1.2746837719426710e-01, -3.8068048285091347e-02, 2.5696082752936417e-02, 1.0691685283171354e-04, 8.6346664914525167e-03, 2.4326667542737546e-03};
static const casadi_real casadi_c2[20] = {0., 0., 0., 0., 2.2222222222222223e+00, 3.3333333333333330e+00, 4.4444444444444446e+00, 6.1111111111111107e+00, 7.7777777777777777e+00, 9.4444444444444446e+00, 1.1666666666666666e+01, 1.3333333333333332e+01, 1.6111111111111111e+01, 1.9444444444444443e+01, 25., 3.3333333333333336e+01, 5.5555555555555557e+01, 5.5555555555555557e+01, 5.5555555555555557e+01, 5.5555555555555557e+01};
static const casadi_real casadi_c3[16] = {1.1422408700313691e-16, -6.7192421935568869e-01, -4.3115156128862309e-01, -4.0743932473373196e-01, -3.3461584461207772e-01, -3.0119702103561768e-01, -2.5641871829839363e-01, -1.6387359326774187e-01, -2.8033209001970133e-01, 6.2801897276157717e-02, 3.9327546777981309e-01, 2.4523305778223559e-01, 3.9274760691946320e-01, 3.9403456903688200e-01, 4.8198024626463909e-01, 5.0000000000000022e-01};

/* jac_mapping:(x,out_f[1x1,0nz])->(jac_f_x) */
static int casadi_f1(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real w0, w1;
  /* #0: @0 = input[0][0] */
  w0 = arg[0] ? arg[0][0] : 0;
  /* #1: @1 = BSpline(@0) */
  casadi_clear((&w1), 1);
  CASADI_PREFIX(nd_boor_eval)((&w1),1,casadi_c0,casadi_s0,casadi_s1,casadi_s2,casadi_c1,1,(&w0),casadi_s3, iw, w);
  /* #2: output[0][0] = @1 */
  if (res[0]) res[0][0] = w1;
  return 0;
}

/* mapping:(x)->(f) */
static int casadi_f2(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real w0, w1;
  /* #0: @0 = input[0][0] */
  w0 = arg[0] ? arg[0][0] : 0;
  /* #1: @1 = BSpline(@0) */
  casadi_clear((&w1), 1);
  CASADI_PREFIX(nd_boor_eval)((&w1),1,casadi_c2,casadi_s4,casadi_s5,casadi_s2,casadi_c3,1,(&w0),casadi_s3, iw, w);
  /* #2: output[0][0] = @1 */
  if (res[0]) res[0][0] = w1;
  return 0;
}

/* mapping:(x)->(f) */
static int casadi_f3(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real w0, w1;
  /* #0: @0 = input[0][0] */
  w0 = arg[0] ? arg[0][0] : 0;
  /* #1: @1 = BSpline(@0) */
  casadi_clear((&w1), 1);
  CASADI_PREFIX(nd_boor_eval)((&w1),1,casadi_c2,casadi_s4,casadi_s5,casadi_s2,casadi_c3,1,(&w0),casadi_s3, iw, w);
  /* #2: output[0][0] = @1 */
  if (res[0]) res[0][0] = w1;
  return 0;
}

/* jac_mapping:(x,out_f[1x1,0nz])->(jac_f_x) */
static int casadi_f4(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real w0, w1;
  /* #0: @0 = input[0][0] */
  w0 = arg[0] ? arg[0][0] : 0;
  /* #1: @1 = BSpline(@0) */
  casadi_clear((&w1), 1);
  CASADI_PREFIX(nd_boor_eval)((&w1),1,casadi_c0,casadi_s0,casadi_s1,casadi_s2,casadi_c1,1,(&w0),casadi_s3, iw, w);
  /* #2: output[0][0] = @1 */
  if (res[0]) res[0][0] = w1;
  return 0;
}

/* Path_parametric_MPC_expl_vde_adj:(i0[8],i1[8],i2,i3[6])->(o0[9x1,7nz]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_int i;
  casadi_real **res1=res+1, *rr;
  const casadi_real **arg1=arg+4, *cs;
  casadi_real w0, w1, w2, w3, *w4=w+16, w5, w6, w7, w8, w9, w10, w11, w12, w13, w15, w16, w17, w18, w19, w20, w21, w22, w23, w24, w25, w26, w27, w28, w29, w30, w31, w32, w33, w34, w35, w36, w37, w38, w39, w40;
  /* #0: @0 = input[0][2] */
  w0 = arg[0] ? arg[0][2] : 0;
  /* #1: @1 = cos(@0) */
  w1 = cos( w0 );
  /* #2: @2 = input[0][3] */
  w2 = arg[0] ? arg[0][3] : 0;
  /* #3: @3 = input[3][5] */
  w3 = arg[3] ? arg[3][5] : 0;
  /* #4: @4 = input[1][0] */
  casadi_copy(arg[1], 8, w4);
  /* #5: @4 = (@3*@4) */
  for (i=0, rr=w4, cs=w4; i<8; ++i) (*rr++)  = (w3*(*cs++));
  /* #6: {@3, @5, @6, @7, @8, @9, @10, NULL} = vertsplit(@4) */
  w3 = w4[0];
  w5 = w4[1];
  w6 = w4[2];
  w7 = w4[3];
  w8 = w4[4];
  w9 = w4[5];
  w10 = w4[6];
  /* #7: @11 = (@2*@5) */
  w11  = (w2*w5);
  /* #8: @1 = (@1*@11) */
  w1 *= w11;
  /* #9: @11 = sin(@0) */
  w11 = sin( w0 );
  /* #10: @12 = input[0][4] */
  w12 = arg[0] ? arg[0][4] : 0;
  /* #11: @13 = (@12*@5) */
  w13  = (w12*w5);
  /* #12: @11 = (@11*@13) */
  w11 *= w13;
  /* #13: @1 = (@1-@11) */
  w1 -= w11;
  /* #14: @11 = cos(@0) */
  w11 = cos( w0 );
  /* #15: @13 = (@12*@3) */
  w13  = (w12*w3);
  /* #16: @11 = (@11*@13) */
  w11 *= w13;
  /* #17: @1 = (@1-@11) */
  w1 -= w11;
  /* #18: @11 = sin(@0) */
  w11 = sin( w0 );
  /* #19: @13 = (@2*@3) */
  w13  = (w2*w3);
  /* #20: @11 = (@11*@13) */
  w11 *= w13;
  /* #21: @1 = (@1-@11) */
  w1 -= w11;
  /* #22: output[0][0] = @1 */
  if (res[0]) res[0][0] = w1;
  /* #23: @14 = 00 */
  /* #24: @1 = jac_mapping(@2, @14) */
  arg1[0]=(&w2);
  arg1[1]=0;
  res1[0]=(&w1);
  if (casadi_f1(arg1, res1, iw, w, 0)) return 1;
  /* #25: @11 = input[0][6] */
  w11 = arg[0] ? arg[0][6] : 0;
  /* #26: @13 = 15.0694 */
  w13 = 1.5069384157767599e+01;
  /* #27: @15 = 1.44323 */
  w15 = 1.4432305676742601e+00;
  /* #28: @16 = mapping(@2) */
  arg1[0]=(&w2);
  res1[0]=(&w16);
  if (casadi_f2(arg1, res1, iw, w, 0)) return 1;
  /* #29: @17 = (@11*@16) */
  w17  = (w11*w16);
  /* #30: @18 = 1.97 */
  w18 = 1.9700000000000000e+00;
  /* #31: @19 = input[0][5] */
  w19 = arg[0] ? arg[0][5] : 0;
  /* #32: @20 = (@18*@19) */
  w20  = (w18*w19);
  /* #33: @20 = (@12-@20) */
  w20  = (w12-w20);
  /* #34: @21 = 0.1 */
  w21 = 1.0000000000000001e-01;
  /* #35: @22 = fmax(@2,@21) */
  w22  = casadi_fmax(w2,w21);
  /* #36: @23 = atan2(@20,@22) */
  w23  = atan2(w20,w22);
  /* #37: @17 = (@17-@23) */
  w17 -= w23;
  /* #38: @17 = (@13*@17) */
  w17  = (w13*w17);
  /* #39: @23 = atan(@17) */
  w23 = atan( w17 );
  /* #40: @23 = (@15*@23) */
  w23  = (w15*w23);
  /* #41: @24 = cos(@23) */
  w24 = cos( w23 );
  /* #42: @25 = 9326.44 */
  w25 = 9.3264444714682304e+03;
  /* #43: @26 = mapping(@2) */
  arg1[0]=(&w2);
  res1[0]=(&w26);
  if (casadi_f3(arg1, res1, iw, w, 0)) return 1;
  /* #44: @27 = (@11*@26) */
  w27  = (w11*w26);
  /* #45: @28 = cos(@27) */
  w28 = cos( w27 );
  /* #46: @29 = 0.000437951 */
  w29 = 4.3795108962231094e-04;
  /* #47: @29 = (@29*@8) */
  w29 *= w8;
  /* #48: @28 = (@28*@29) */
  w28 *= w29;
  /* #49: @30 = 1.97 */
  w30 = 1.9700000000000000e+00;
  /* #50: @31 = cos(@27) */
  w31 = cos( w27 );
  /* #51: @32 = 0.000215054 */
  w32 = 2.1505376344086021e-04;
  /* #52: @32 = (@32*@9) */
  w32 *= w9;
  /* #53: @31 = (@31*@32) */
  w31 *= w32;
  /* #54: @31 = (@30*@31) */
  w31  = (w30*w31);
  /* #55: @28 = (@28-@31) */
  w28 -= w31;
  /* #56: @31 = sin(@27) */
  w31 = sin( w27 );
  /* #57: @9 = 0.000437951 */
  w9 = 4.3795108962231094e-04;
  /* #58: @9 = (@9*@7) */
  w9 *= w7;
  /* #59: @31 = (@31*@9) */
  w31 *= w9;
  /* #60: @28 = (@28-@31) */
  w28 -= w31;
  /* #61: @28 = (@25*@28) */
  w28  = (w25*w28);
  /* #62: @24 = (@24*@28) */
  w24 *= w28;
  /* #63: @15 = (@15*@24) */
  w15 *= w24;
  /* #64: @24 = 1 */
  w24 = 1.;
  /* #65: @17 = sq(@17) */
  w17 = casadi_sq( w17 );
  /* #66: @24 = (@24+@17) */
  w24 += w17;
  /* #67: @15 = (@15/@24) */
  w15 /= w24;
  /* #68: @13 = (@13*@15) */
  w13 *= w15;
  /* #69: @15 = (@11*@13) */
  w15  = (w11*w13);
  /* #70: @1 = (@1*@15) */
  w1 *= w15;
  /* #71: @15 = (@19*@8) */
  w15  = (w19*w8);
  /* #72: @1 = (@1-@15) */
  w1 -= w15;
  /* #73: @15 = (@21<=@2) */
  w15  = (w21<=w2);
  /* #74: @21 = (@2<=@21) */
  w21  = (w2<=w21);
  /* #75: @21 = (@15+@21) */
  w21  = (w15+w21);
  /* #76: @15 = (@15/@21) */
  w15 /= w21;
  /* #77: @21 = sq(@20) */
  w21 = casadi_sq( w20 );
  /* #78: @24 = sq(@22) */
  w24 = casadi_sq( w22 );
  /* #79: @21 = (@21+@24) */
  w21 += w24;
  /* #80: @20 = (@20/@21) */
  w20 /= w21;
  /* #81: @20 = (@20*@13) */
  w20 *= w13;
  /* #82: @24 = 0.985 */
  w24 = 9.8499999999999999e-01;
  /* #83: @17 = (@24*@19) */
  w17  = (w24*w19);
  /* #84: @17 = (@12+@17) */
  w17  = (w12+w17);
  /* #85: @28 = sq(@17) */
  w28 = casadi_sq( w17 );
  /* #86: @31 = sq(@22) */
  w31 = casadi_sq( w22 );
  /* #87: @28 = (@28+@31) */
  w28 += w31;
  /* #88: @31 = (@17/@28) */
  w31  = (w17/w28);
  /* #89: @33 = 13.1632 */
  w33 = 1.3163204541541001e+01;
  /* #90: @34 = 1.45027 */
  w34 = 1.4502715506375901e+00;
  /* #91: @17 = atan2(@17,@22) */
  w17  = atan2(w17,w22);
  /* #92: @17 = (@11-@17) */
  w17  = (w11-w17);
  /* #93: @17 = (@33*@17) */
  w17  = (w33*w17);
  /* #94: @35 = atan(@17) */
  w35 = atan( w17 );
  /* #95: @35 = (@34*@35) */
  w35  = (w34*w35);
  /* #96: @36 = cos(@35) */
  w36 = cos( w35 );
  /* #97: @37 = 9032.92 */
  w37 = 9.0329197556223498e+03;
  /* #98: @38 = 0.985 */
  w38 = 9.8499999999999999e-01;
  /* #99: @39 = cos(@11) */
  w39 = cos( w11 );
  /* #100: @39 = (@39*@32) */
  w39 *= w32;
  /* #101: @39 = (@38*@39) */
  w39  = (w38*w39);
  /* #102: @40 = cos(@11) */
  w40 = cos( w11 );
  /* #103: @40 = (@40*@29) */
  w40 *= w29;
  /* #104: @39 = (@39+@40) */
  w39 += w40;
  /* #105: @40 = sin(@11) */
  w40 = sin( w11 );
  /* #106: @40 = (@40*@9) */
  w40 *= w9;
  /* #107: @39 = (@39-@40) */
  w39 -= w40;
  /* #108: @39 = (@37*@39) */
  w39  = (w37*w39);
  /* #109: @36 = (@36*@39) */
  w36 *= w39;
  /* #110: @34 = (@34*@36) */
  w34 *= w36;
  /* #111: @36 = 1 */
  w36 = 1.;
  /* #112: @17 = sq(@17) */
  w17 = casadi_sq( w17 );
  /* #113: @36 = (@36+@17) */
  w36 += w17;
  /* #114: @34 = (@34/@36) */
  w34 /= w36;
  /* #115: @33 = (@33*@34) */
  w33 *= w34;
  /* #116: @31 = (@31*@33) */
  w31 *= w33;
  /* #117: @20 = (@20+@31) */
  w20 += w31;
  /* #118: @15 = (@15*@20) */
  w15 *= w20;
  /* #119: @1 = (@1+@15) */
  w1 += w15;
  /* #120: @14 = 00 */
  /* #121: @15 = jac_mapping(@2, @14) */
  arg1[0]=(&w2);
  arg1[1]=0;
  res1[0]=(&w15);
  if (casadi_f4(arg1, res1, iw, w, 0)) return 1;
  /* #122: @20 = sin(@27) */
  w20 = sin( w27 );
  /* #123: @23 = sin(@23) */
  w23 = sin( w23 );
  /* #124: @25 = (@25*@23) */
  w25 *= w23;
  /* #125: @30 = (@30*@25) */
  w30 *= w25;
  /* #126: @30 = (@30*@32) */
  w30 *= w32;
  /* #127: @20 = (@20*@30) */
  w20 *= w30;
  /* #128: @30 = cos(@27) */
  w30 = cos( w27 );
  /* #129: @23 = 1.97 */
  w23 = 1.9700000000000000e+00;
  /* #130: @31 = input[0][7] */
  w31 = arg[0] ? arg[0][7] : 0;
  /* #131: @34 = 0.36875 */
  w34 = 3.6875000000000002e-01;
  /* #132: @31 = (@31/@34) */
  w31 /= w34;
  /* #133: @34 = 73.457 */
  w34 = 7.3456974659287212e+01;
  /* #134: @31 = (@31-@34) */
  w31 -= w34;
  /* #135: @34 = (@23*@31) */
  w34  = (w23*w31);
  /* #136: @34 = (@34*@32) */
  w34 *= w32;
  /* #137: @30 = (@30*@34) */
  w30 *= w34;
  /* #138: @20 = (@20-@30) */
  w20 -= w30;
  /* #139: @30 = sin(@27) */
  w30 = sin( w27 );
  /* #140: @34 = (@25*@29) */
  w34  = (w25*w29);
  /* #141: @30 = (@30*@34) */
  w30 *= w34;
  /* #142: @20 = (@20-@30) */
  w20 -= w30;
  /* #143: @30 = cos(@27) */
  w30 = cos( w27 );
  /* #144: @34 = (@31*@29) */
  w34  = (w31*w29);
  /* #145: @30 = (@30*@34) */
  w30 *= w34;
  /* #146: @20 = (@20+@30) */
  w20 += w30;
  /* #147: @30 = cos(@27) */
  w30 = cos( w27 );
  /* #148: @25 = (@25*@9) */
  w25 *= w9;
  /* #149: @30 = (@30*@25) */
  w30 *= w25;
  /* #150: @20 = (@20-@30) */
  w20 -= w30;
  /* #151: @30 = sin(@27) */
  w30 = sin( w27 );
  /* #152: @31 = (@31*@9) */
  w31 *= w9;
  /* #153: @30 = (@30*@31) */
  w30 *= w31;
  /* #154: @20 = (@20-@30) */
  w20 -= w30;
  /* #155: @30 = (@11*@20) */
  w30  = (w11*w20);
  /* #156: @15 = (@15*@30) */
  w15 *= w30;
  /* #157: @1 = (@1+@15) */
  w1 += w15;
  /* #158: @15 = sin(@0) */
  w15 = sin( w0 );
  /* #159: @15 = (@15*@5) */
  w15 *= w5;
  /* #160: @1 = (@1+@15) */
  w1 += w15;
  /* #161: @15 = cos(@0) */
  w15 = cos( w0 );
  /* #162: @15 = (@15*@3) */
  w15 *= w3;
  /* #163: @1 = (@1+@15) */
  w1 += w15;
  /* #164: output[0][1] = @1 */
  if (res[0]) res[0][1] = w1;
  /* #165: @19 = (@19*@7) */
  w19 *= w7;
  /* #166: @21 = (@22/@21) */
  w21  = (w22/w21);
  /* #167: @21 = (@21*@13) */
  w21 *= w13;
  /* #168: @19 = (@19-@21) */
  w19 -= w21;
  /* #169: @22 = (@22/@28) */
  w22 /= w28;
  /* #170: @22 = (@22*@33) */
  w22 *= w33;
  /* #171: @19 = (@19-@22) */
  w19 -= w22;
  /* #172: @28 = cos(@0) */
  w28 = cos( w0 );
  /* #173: @28 = (@28*@5) */
  w28 *= w5;
  /* #174: @19 = (@19+@28) */
  w19 += w28;
  /* #175: @0 = sin(@0) */
  w0 = sin( w0 );
  /* #176: @0 = (@0*@3) */
  w0 *= w3;
  /* #177: @19 = (@19-@0) */
  w19 -= w0;
  /* #178: output[0][2] = @19 */
  if (res[0]) res[0][2] = w19;
  /* #179: @2 = (@2*@8) */
  w2 *= w8;
  /* #180: @6 = (@6-@2) */
  w6 -= w2;
  /* #181: @12 = (@12*@7) */
  w12 *= w7;
  /* #182: @6 = (@6+@12) */
  w6 += w12;
  /* #183: @18 = (@18*@21) */
  w18 *= w21;
  /* #184: @6 = (@6+@18) */
  w6 += w18;
  /* #185: @24 = (@24*@22) */
  w24 *= w22;
  /* #186: @6 = (@6-@24) */
  w6 -= w24;
  /* #187: output[0][3] = @6 */
  if (res[0]) res[0][3] = w6;
  /* #188: @6 = sin(@11) */
  w6 = sin( w11 );
  /* #189: @35 = sin(@35) */
  w35 = sin( w35 );
  /* #190: @37 = (@37*@35) */
  w37 *= w35;
  /* #191: @35 = (@37*@29) */
  w35  = (w37*w29);
  /* #192: @6 = (@6*@35) */
  w6 *= w35;
  /* #193: @6 = (-@6) */
  w6 = (- w6 );
  /* #194: @35 = sin(@11) */
  w35 = sin( w11 );
  /* #195: @38 = (@38*@37) */
  w38 *= w37;
  /* #196: @38 = (@38*@32) */
  w38 *= w32;
  /* #197: @35 = (@35*@38) */
  w35 *= w38;
  /* #198: @6 = (@6-@35) */
  w6 -= w35;
  /* #199: @16 = (@16*@13) */
  w16 *= w13;
  /* #200: @6 = (@6+@16) */
  w6 += w16;
  /* #201: @11 = cos(@11) */
  w11 = cos( w11 );
  /* #202: @37 = (@37*@9) */
  w37 *= w9;
  /* #203: @11 = (@11*@37) */
  w11 *= w37;
  /* #204: @6 = (@6-@11) */
  w6 -= w11;
  /* #205: @6 = (@6+@33) */
  w6 += w33;
  /* #206: @26 = (@26*@20) */
  w26 *= w20;
  /* #207: @6 = (@6+@26) */
  w6 += w26;
  /* #208: output[0][4] = @6 */
  if (res[0]) res[0][4] = w6;
  /* #209: @6 = 2.71186 */
  w6 = 2.7118644067796609e+00;
  /* #210: @26 = sin(@27) */
  w26 = sin( w27 );
  /* #211: @26 = (@26*@29) */
  w26 *= w29;
  /* #212: @29 = sin(@27) */
  w29 = sin( w27 );
  /* #213: @29 = (@29*@32) */
  w29 *= w32;
  /* #214: @23 = (@23*@29) */
  w23 *= w29;
  /* #215: @26 = (@26-@23) */
  w26 -= w23;
  /* #216: @27 = cos(@27) */
  w27 = cos( w27 );
  /* #217: @27 = (@27*@9) */
  w27 *= w9;
  /* #218: @26 = (@26+@27) */
  w26 += w27;
  /* #219: @6 = (@6*@26) */
  w6 *= w26;
  /* #220: output[0][5] = @6 */
  if (res[0]) res[0][5] = w6;
  /* #221: output[0][6] = @10 */
  if (res[0]) res[0][6] = w10;
  return 0;
}

CASADI_SYMBOL_EXPORT int Path_parametric_MPC_expl_vde_adj(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int Path_parametric_MPC_expl_vde_adj_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int Path_parametric_MPC_expl_vde_adj_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void Path_parametric_MPC_expl_vde_adj_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int Path_parametric_MPC_expl_vde_adj_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void Path_parametric_MPC_expl_vde_adj_release(int mem) {
}

CASADI_SYMBOL_EXPORT void Path_parametric_MPC_expl_vde_adj_incref(void) {
}

CASADI_SYMBOL_EXPORT void Path_parametric_MPC_expl_vde_adj_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int Path_parametric_MPC_expl_vde_adj_n_in(void) { return 4;}

CASADI_SYMBOL_EXPORT casadi_int Path_parametric_MPC_expl_vde_adj_n_out(void) { return 1;}

CASADI_SYMBOL_EXPORT casadi_real Path_parametric_MPC_expl_vde_adj_default_in(casadi_int i) {
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* Path_parametric_MPC_expl_vde_adj_name_in(casadi_int i) {
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    case 3: return "i3";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* Path_parametric_MPC_expl_vde_adj_name_out(casadi_int i) {
  switch (i) {
    case 0: return "o0";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* Path_parametric_MPC_expl_vde_adj_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s6;
    case 1: return casadi_s6;
    case 2: return casadi_s7;
    case 3: return casadi_s8;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* Path_parametric_MPC_expl_vde_adj_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s9;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int Path_parametric_MPC_expl_vde_adj_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 7;
  if (sz_res) *sz_res = 9;
  if (sz_iw) *sz_iw = 8;
  if (sz_w) *sz_w = 59;
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
