/* This file was automatically generated by CasADi 3.6.3.
 *  It consists of: 
 *   1) content generated by CasADi runtime: not copyrighted
 *   2) template code copied from CasADi source: permissively licensed (MIT-0)
 *   3) user code: owned by the user
 *
 */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) Path_parametric_MPC_expl_vde_forw_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int int
#endif

/* Add prefix to internal symbols */
#define casadi_c0 CASADI_PREFIX(c0)
#define casadi_c1 CASADI_PREFIX(c1)
#define casadi_c2 CASADI_PREFIX(c2)
#define casadi_c3 CASADI_PREFIX(c3)
#define casadi_clear CASADI_PREFIX(clear)
#define casadi_clear_casadi_int CASADI_PREFIX(clear_casadi_int)
#define casadi_copy CASADI_PREFIX(copy)
#define casadi_de_boor CASADI_PREFIX(de_boor)
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_f1 CASADI_PREFIX(f1)
#define casadi_f2 CASADI_PREFIX(f2)
#define casadi_f3 CASADI_PREFIX(f3)
#define casadi_f4 CASADI_PREFIX(f4)
#define casadi_f5 CASADI_PREFIX(f5)
#define casadi_f6 CASADI_PREFIX(f6)
#define casadi_fill CASADI_PREFIX(fill)
#define casadi_fill_casadi_int CASADI_PREFIX(fill_casadi_int)
#define casadi_fmax CASADI_PREFIX(fmax)
#define casadi_low CASADI_PREFIX(low)
#define casadi_nd_boor_eval CASADI_PREFIX(nd_boor_eval)
#define casadi_project CASADI_PREFIX(project)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_s10 CASADI_PREFIX(s10)
#define casadi_s11 CASADI_PREFIX(s11)
#define casadi_s12 CASADI_PREFIX(s12)
#define casadi_s13 CASADI_PREFIX(s13)
#define casadi_s2 CASADI_PREFIX(s2)
#define casadi_s3 CASADI_PREFIX(s3)
#define casadi_s4 CASADI_PREFIX(s4)
#define casadi_s5 CASADI_PREFIX(s5)
#define casadi_s6 CASADI_PREFIX(s6)
#define casadi_s7 CASADI_PREFIX(s7)
#define casadi_s8 CASADI_PREFIX(s8)
#define casadi_s9 CASADI_PREFIX(s9)
#define casadi_sq CASADI_PREFIX(sq)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

void casadi_de_boor(casadi_real x, const casadi_real* knots, casadi_int n_knots, casadi_int degree, casadi_real* boor) {
  casadi_int d, i;
  for (d=1;d<degree+1;++d) {
    for (i=0;i<n_knots-d-1;++i) {
      casadi_real b, bottom;
      b = 0;
      bottom = knots[i + d] - knots[i];
      if (bottom) b = (x - knots[i]) * boor[i] / bottom;
      bottom = knots[i + d + 1] - knots[i + 1];
      if (bottom) b += (knots[i + d + 1] - x) * boor[i + 1] / bottom;
      boor[i] = b;
    }
  }
}

void casadi_fill(casadi_real* x, casadi_int n, casadi_real alpha) {
  casadi_int i;
  if (x) {
    for (i=0; i<n; ++i) *x++ = alpha;
  }
}

void casadi_fill_casadi_int(casadi_int* x, casadi_int n, casadi_int alpha) {
  casadi_int i;
  if (x) {
    for (i=0; i<n; ++i) *x++ = alpha;
  }
}

void casadi_clear(casadi_real* x, casadi_int n) {
  casadi_int i;
  if (x) {
    for (i=0; i<n; ++i) *x++ = 0;
  }
}

void casadi_clear_casadi_int(casadi_int* x, casadi_int n) {
  casadi_int i;
  if (x) {
    for (i=0; i<n; ++i) *x++ = 0;
  }
}

casadi_int casadi_low(casadi_real x, const casadi_real* grid, casadi_int ng, casadi_int lookup_mode) {
  switch (lookup_mode) {
    case 1:
      {
        casadi_real g0, dg;
        casadi_int ret;
        g0 = grid[0];
        dg = grid[ng-1]-g0;
        ret = (casadi_int) ((x-g0)*(ng-1)/dg);
        if (ret<0) ret=0;
        if (ret>ng-2) ret=ng-2;
        return ret;
      }
    case 2:
      {
        casadi_int start, stop, pivot;
        if (ng<2 || x<grid[1]) return 0;
        if (x>grid[ng-1]) return ng-2;
        start = 0;
        stop  = ng-1;
        while (1) {
          pivot = (stop+start)/2;
          if (x < grid[pivot]) {
            if (pivot==stop) return pivot;
            stop = pivot;
          } else {
            if (pivot==start) return pivot;
            start = pivot;
          }
        }
      }
    default:
      {
        casadi_int i;
        for (i=0; i<ng-2; ++i) {
          if (x < grid[i+1]) break;
        }
        return i;
      }
  }
}

void casadi_nd_boor_eval(casadi_real* ret, casadi_int n_dims, const casadi_real* all_knots, const casadi_int* offset, const casadi_int* all_degree, const casadi_int* strides, const casadi_real* c, casadi_int m, const casadi_real* all_x, const casadi_int* lookup_mode, casadi_int* iw, casadi_real* w) {
  casadi_int n_iter, k, i, pivot;
  casadi_int *boor_offset, *starts, *index, *coeff_offset;
  casadi_real *cumprod, *all_boor;
  boor_offset = iw; iw+=n_dims+1;
  starts = iw; iw+=n_dims;
  index = iw; iw+=n_dims;
  coeff_offset = iw;
  cumprod = w; w+= n_dims+1;
  all_boor = w;
  boor_offset[0] = 0;
  cumprod[n_dims] = 1;
  coeff_offset[n_dims] = 0;
  n_iter = 1;
  for (k=0;k<n_dims;++k) {
    casadi_real *boor;
    const casadi_real* knots;
    casadi_real x;
    casadi_int degree, n_knots, n_b, L, start;
    boor = all_boor+boor_offset[k];
    degree = all_degree[k];
    knots = all_knots + offset[k];
    n_knots = offset[k+1]-offset[k];
    n_b = n_knots-degree-1;
    x = all_x[k];
    L = casadi_low(x, knots+degree, n_knots-2*degree, lookup_mode[k]);
    start = L;
    if (start>n_b-degree-1) start = n_b-degree-1;
    starts[k] = start;
    casadi_clear(boor, 2*degree+1);
    if (x>=knots[0] && x<=knots[n_knots-1]) {
      if (x==knots[1]) {
        casadi_fill(boor, degree+1, 1.0);
      } else if (x==knots[n_knots-1]) {
        boor[degree] = 1;
      } else if (knots[L+degree]==x) {
        boor[degree-1] = 1;
      } else {
        boor[degree] = 1;
      }
    }
    casadi_de_boor(x, knots+start, 2*degree+2, degree, boor);
    boor+= degree+1;
    n_iter*= degree+1;
    boor_offset[k+1] = boor_offset[k] + degree+1;
  }
  casadi_clear_casadi_int(index, n_dims);
  for (pivot=n_dims-1;pivot>=0;--pivot) {
    cumprod[pivot] = (*(all_boor+boor_offset[pivot]))*cumprod[pivot+1];
    coeff_offset[pivot] = starts[pivot]*strides[pivot]+coeff_offset[pivot+1];
  }
  for (k=0;k<n_iter;++k) {
    casadi_int pivot = 0;
    for (i=0;i<m;++i) ret[i] += c[coeff_offset[0]+i]*cumprod[0];
    index[0]++;
    {
      while (index[pivot]==boor_offset[pivot+1]-boor_offset[pivot]) {
        index[pivot] = 0;
        if (pivot==n_dims-1) break;
        index[++pivot]++;
      }
      while (pivot>0) {
        cumprod[pivot] = (*(all_boor+boor_offset[pivot]+index[pivot]))*cumprod[pivot+1];
        coeff_offset[pivot] = (starts[pivot]+index[pivot])*strides[pivot]+coeff_offset[pivot+1];
        pivot--;
      }
    }
    cumprod[0] = (*(all_boor+index[0]))*cumprod[1];
    coeff_offset[0] = (starts[0]+index[0])*m+coeff_offset[1];
  }
}

casadi_real casadi_fmax(casadi_real x, casadi_real y) {
/* Pre-c99 compatibility */
#if __STDC_VERSION__ < 199901L
  return x>y ? x : y;
#else
  return fmax(x, y);
#endif
}

void casadi_copy(const casadi_real* x, casadi_int n, casadi_real* y) {
  casadi_int i;
  if (y) {
    if (x) {
      for (i=0; i<n; ++i) *y++ = *x++;
    } else {
      for (i=0; i<n; ++i) *y++ = 0.;
    }
  }
}

casadi_real casadi_sq(casadi_real x) { return x*x;}

void casadi_project(const casadi_real* x, const casadi_int* sp_x, casadi_real* y, const casadi_int* sp_y, casadi_real* w) {
  casadi_int ncol_x, ncol_y, i, el;
  const casadi_int *colind_x, *row_x, *colind_y, *row_y;
  ncol_x = sp_x[1];
  colind_x = sp_x+2; row_x = sp_x + 2 + ncol_x+1;
  ncol_y = sp_y[1];
  colind_y = sp_y+2; row_y = sp_y + 2 + ncol_y+1;
  for (i=0; i<ncol_x; ++i) {
    for (el=colind_y[i]; el<colind_y[i+1]; ++el) w[row_y[el]] = 0;
    for (el=colind_x[i]; el<colind_x[i+1]; ++el) w[row_x[el]] = x[el];
    for (el=colind_y[i]; el<colind_y[i+1]; ++el) y[el] = w[row_y[el]];
  }
}

static const casadi_int casadi_s0[2] = {0, 20};
static const casadi_int casadi_s1[1] = {3};
static const casadi_int casadi_s2[1] = {1};
static const casadi_int casadi_s3[1] = {0};
static const casadi_int casadi_s4[2] = {0, 18};
static const casadi_int casadi_s5[1] = {2};
static const casadi_int casadi_s6[5] = {8, 1, 0, 1, 6};
static const casadi_int casadi_s7[11] = {8, 1, 0, 7, 0, 1, 2, 3, 4, 5, 6};
static const casadi_int casadi_s8[10] = {8, 1, 0, 6, 0, 1, 2, 3, 4, 5};
static const casadi_int casadi_s9[12] = {8, 1, 0, 8, 0, 1, 2, 3, 4, 5, 6, 7};
static const casadi_int casadi_s10[75] = {8, 8, 0, 8, 16, 24, 32, 40, 48, 56, 64, 0, 1, 2, 3, 4, 5, 6, 7, 0, 1, 2, 3, 4, 5, 6, 7, 0, 1, 2, 3, 4, 5, 6, 7, 0, 1, 2, 3, 4, 5, 6, 7, 0, 1, 2, 3, 4, 5, 6, 7, 0, 1, 2, 3, 4, 5, 6, 7, 0, 1, 2, 3, 4, 5, 6, 7, 0, 1, 2, 3, 4, 5, 6, 7};
static const casadi_int casadi_s11[5] = {1, 1, 0, 1, 0};
static const casadi_int casadi_s12[10] = {6, 1, 0, 6, 0, 1, 2, 3, 4, 5};
static const casadi_int casadi_s13[59] = {8, 8, 0, 6, 12, 18, 24, 30, 36, 42, 48, 0, 1, 2, 3, 4, 5, 0, 1, 2, 3, 4, 5, 0, 1, 2, 3, 4, 5, 0, 1, 2, 3, 4, 5, 0, 1, 2, 3, 4, 5, 0, 1, 2, 3, 4, 5, 0, 1, 2, 3, 4, 5, 0, 1, 2, 3, 4, 5};

static const casadi_real casadi_c0[20] = {0., 0., 0., 0., 2.2222222222222223e+00, 3.3333333333333330e+00, 4.4444444444444446e+00, 6.1111111111111107e+00, 7.7777777777777777e+00, 9.4444444444444446e+00, 1.1666666666666666e+01, 1.3333333333333332e+01, 1.6111111111111111e+01, 1.9444444444444443e+01, 25., 3.3333333333333336e+01, 5.5555555555555557e+01, 5.5555555555555557e+01, 5.5555555555555557e+01, 5.5555555555555557e+01};
static const casadi_real casadi_c1[16] = {1.1422408700313691e-16, -6.7192421935568869e-01, -4.3115156128862309e-01, -4.0743932473373196e-01, -3.3461584461207772e-01, -3.0119702103561768e-01, -2.5641871829839363e-01, -1.6387359326774187e-01, -2.8033209001970133e-01, 6.2801897276157717e-02, 3.9327546777981309e-01, 2.4523305778223559e-01, 3.9274760691946320e-01, 3.9403456903688200e-01, 4.8198024626463909e-01, 5.0000000000000022e-01};
static const casadi_real casadi_c2[18] = {0., 0., 0., 2.2222222222222223e+00, 3.3333333333333330e+00, 4.4444444444444446e+00, 6.1111111111111107e+00, 7.7777777777777777e+00, 9.4444444444444446e+00, 1.1666666666666666e+01, 1.3333333333333332e+01, 1.6111111111111111e+01, 1.9444444444444443e+01, 25., 3.3333333333333336e+01, 5.5555555555555557e+01, 5.5555555555555557e+01, 5.5555555555555557e+01};
static const casadi_real casadi_c3[15] = {-9.0709769613017976e-01, 2.1669539226035911e-01, 1.6005759674551534e-02, 5.6178113236704741e-02, 2.2557705914110521e-02, 2.6866981642334448e-02, 4.9974367516551946e-02, -6.2887588246058140e-02, 1.5441029428313660e-01, 1.2746837719426710e-01, -3.8068048285091347e-02, 2.5696082752936417e-02, 1.0691685283171354e-04, 8.6346664914525167e-03, 2.4326667542737546e-03};

/* mapping:(x)->(f) */
static int casadi_f1(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real w0, w1;
  /* #0: @0 = input[0][0] */
  w0 = arg[0] ? arg[0][0] : 0;
  /* #1: @1 = BSpline(@0) */
  casadi_clear((&w1), 1);
  CASADI_PREFIX(nd_boor_eval)((&w1),1,casadi_c0,casadi_s0,casadi_s1,casadi_s2,casadi_c1,1,(&w0),casadi_s3, iw, w);
  /* #2: output[0][0] = @1 */
  if (res[0]) res[0][0] = w1;
  return 0;
}

/* mapping:(x)->(f) */
static int casadi_f2(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real w0, w1;
  /* #0: @0 = input[0][0] */
  w0 = arg[0] ? arg[0][0] : 0;
  /* #1: @1 = BSpline(@0) */
  casadi_clear((&w1), 1);
  CASADI_PREFIX(nd_boor_eval)((&w1),1,casadi_c0,casadi_s0,casadi_s1,casadi_s2,casadi_c1,1,(&w0),casadi_s3, iw, w);
  /* #2: output[0][0] = @1 */
  if (res[0]) res[0][0] = w1;
  return 0;
}

/* jac_mapping:(x,out_f[1x1,0nz])->(jac_f_x) */
static int casadi_f3(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real w0, w1;
  /* #0: @0 = input[0][0] */
  w0 = arg[0] ? arg[0][0] : 0;
  /* #1: @1 = BSpline(@0) */
  casadi_clear((&w1), 1);
  CASADI_PREFIX(nd_boor_eval)((&w1),1,casadi_c2,casadi_s4,casadi_s5,casadi_s2,casadi_c3,1,(&w0),casadi_s3, iw, w);
  /* #2: output[0][0] = @1 */
  if (res[0]) res[0][0] = w1;
  return 0;
}

/* jac_mapping:(x,out_f[1x1,0nz])->(jac_f_x) */
static int casadi_f4(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real w0, w1;
  /* #0: @0 = input[0][0] */
  w0 = arg[0] ? arg[0][0] : 0;
  /* #1: @1 = BSpline(@0) */
  casadi_clear((&w1), 1);
  CASADI_PREFIX(nd_boor_eval)((&w1),1,casadi_c2,casadi_s4,casadi_s5,casadi_s2,casadi_c3,1,(&w0),casadi_s3, iw, w);
  /* #2: output[0][0] = @1 */
  if (res[0]) res[0][0] = w1;
  return 0;
}

/* fwd1_mapping:(x,out_f[1x1,0nz],fwd_x)->(fwd_f) */
static int casadi_f5(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real w0, w1;
  /* #0: @0 = input[0][0] */
  w0 = arg[0] ? arg[0][0] : 0;
  /* #1: @1 = BSpline(@0) */
  casadi_clear((&w1), 1);
  CASADI_PREFIX(nd_boor_eval)((&w1),1,casadi_c2,casadi_s4,casadi_s5,casadi_s2,casadi_c3,1,(&w0),casadi_s3, iw, w);
  /* #2: @0 = input[2][0] */
  w0 = arg[2] ? arg[2][0] : 0;
  /* #3: @1 = (@1*@0) */
  w1 *= w0;
  /* #4: output[0][0] = @1 */
  if (res[0]) res[0][0] = w1;
  return 0;
}

/* fwd1_mapping:(x,out_f[1x1,0nz],fwd_x)->(fwd_f) */
static int casadi_f6(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real w0, w1;
  /* #0: @0 = input[0][0] */
  w0 = arg[0] ? arg[0][0] : 0;
  /* #1: @1 = BSpline(@0) */
  casadi_clear((&w1), 1);
  CASADI_PREFIX(nd_boor_eval)((&w1),1,casadi_c2,casadi_s4,casadi_s5,casadi_s2,casadi_c3,1,(&w0),casadi_s3, iw, w);
  /* #2: @0 = input[2][0] */
  w0 = arg[2] ? arg[2][0] : 0;
  /* #3: @1 = (@1*@0) */
  w1 *= w0;
  /* #4: output[0][0] = @1 */
  if (res[0]) res[0][0] = w1;
  return 0;
}

/* Path_parametric_MPC_expl_vde_forw:(i0[8],i1[8x8],i2[8],i3,i4[6])->(o0[8],o1[8x8,48nz],o2[8x1,7nz]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_int i;
  casadi_real **res1=res+3, *rr, *ss;
  const casadi_real **arg1=arg+5, *cs;
  casadi_real w0, w1, w2, w3, w4, w5, w6, w7, w8, w9, w10, w11, w12, w13, w14, w15, w16, w17, w18, w19, w20, w21, w22, w23, w24, w25, w26, w27, w28, w29, w30, w31, w32, w33, w34, w35, w36, w37, w38, w39, w40, w41, w42, w43, w44, w45, w46, w47, w48, w49, w50, w51, w52, w53, *w54=w+66, *w55=w+74, *w56=w+138, *w57=w+146, *w58=w+154, *w59=w+162, *w60=w+170, *w61=w+178, *w62=w+186, w63, w64, w65, w66, w67, w68, w69, w70, w71, w73, w74, w75, w76, w77, w78, w79, w80, w81, w82, w83, w84, w85, w86, w87, w88, w89, w90, w91, w92, w93, w94, w95, w96, w97, w98, w99, w100, w101, w102, w103, w104, w105, w106, w107, w108, w109, w110, w111, w112, w113, w114, w115, w116, w117, w118, w119, w120, w121, w122, w123, w124, w125, w126, w127, w128, w129, w130, w131, w132, w133, w134, w135, w136, w137, w138, w139, w140, w141, w142, w143, w144, w145, w146, w147, *w149=w+278, *w155=w+284, *w156=w+291;
  /* #0: @0 = input[4][5] */
  w0 = arg[4] ? arg[4][5] : 0;
  /* #1: @1 = input[0][3] */
  w1 = arg[0] ? arg[0][3] : 0;
  /* #2: @2 = input[0][2] */
  w2 = arg[0] ? arg[0][2] : 0;
  /* #3: @3 = cos(@2) */
  w3 = cos( w2 );
  /* #4: @4 = (@1*@3) */
  w4  = (w1*w3);
  /* #5: @5 = input[0][4] */
  w5 = arg[0] ? arg[0][4] : 0;
  /* #6: @6 = sin(@2) */
  w6 = sin( w2 );
  /* #7: @7 = (@5*@6) */
  w7  = (w5*w6);
  /* #8: @4 = (@4-@7) */
  w4 -= w7;
  /* #9: @7 = sin(@2) */
  w7 = sin( w2 );
  /* #10: @8 = (@1*@7) */
  w8  = (w1*w7);
  /* #11: @9 = cos(@2) */
  w9 = cos( w2 );
  /* #12: @10 = (@5*@9) */
  w10  = (w5*w9);
  /* #13: @8 = (@8+@10) */
  w8 += w10;
  /* #14: @10 = input[0][5] */
  w10 = arg[0] ? arg[0][5] : 0;
  /* #15: @11 = input[0][7] */
  w11 = arg[0] ? arg[0][7] : 0;
  /* #16: @12 = 0.36875 */
  w12 = 3.6875000000000002e-01;
  /* #17: @11 = (@11/@12) */
  w11 /= w12;
  /* #18: @12 = 73.457 */
  w12 = 7.3456974659287212e+01;
  /* #19: @11 = (@11-@12) */
  w11 -= w12;
  /* #20: @12 = input[0][6] */
  w12 = arg[0] ? arg[0][6] : 0;
  /* #21: @13 = mapping(@1) */
  arg1[0]=(&w1);
  res1[0]=(&w13);
  if (casadi_f1(arg1, res1, iw, w, 0)) return 1;
  /* #22: @14 = (@12*@13) */
  w14  = (w12*w13);
  /* #23: @15 = cos(@14) */
  w15 = cos( w14 );
  /* #24: @16 = (@11*@15) */
  w16  = (w11*w15);
  /* #25: @17 = 9032.92 */
  w17 = 9.0329197556223498e+03;
  /* #26: @18 = 1.45027 */
  w18 = 1.4502715506375901e+00;
  /* #27: @19 = 13.1632 */
  w19 = 1.3163204541541001e+01;
  /* #28: @20 = 0.985 */
  w20 = 9.8499999999999999e-01;
  /* #29: @21 = (@20*@10) */
  w21  = (w20*w10);
  /* #30: @21 = (@5+@21) */
  w21  = (w5+w21);
  /* #31: @22 = 0.1 */
  w22 = 1.0000000000000001e-01;
  /* #32: @23 = fmax(@1,@22) */
  w23  = casadi_fmax(w1,w22);
  /* #33: @24 = atan2(@21,@23) */
  w24  = atan2(w21,w23);
  /* #34: @24 = (@12-@24) */
  w24  = (w12-w24);
  /* #35: @24 = (@19*@24) */
  w24  = (w19*w24);
  /* #36: @25 = atan(@24) */
  w25 = atan( w24 );
  /* #37: @25 = (@18*@25) */
  w25  = (w18*w25);
  /* #38: @26 = sin(@25) */
  w26 = sin( w25 );
  /* #39: @26 = (@17*@26) */
  w26  = (w17*w26);
  /* #40: @27 = sin(@12) */
  w27 = sin( w12 );
  /* #41: @28 = (@26*@27) */
  w28  = (w26*w27);
  /* #42: @16 = (@16-@28) */
  w16 -= w28;
  /* #43: @28 = 9326.44 */
  w28 = 9.3264444714682304e+03;
  /* #44: @29 = 1.44323 */
  w29 = 1.4432305676742601e+00;
  /* #45: @30 = 15.0694 */
  w30 = 1.5069384157767599e+01;
  /* #46: @31 = mapping(@1) */
  arg1[0]=(&w1);
  res1[0]=(&w31);
  if (casadi_f2(arg1, res1, iw, w, 0)) return 1;
  /* #47: @32 = (@12*@31) */
  w32  = (w12*w31);
  /* #48: @33 = 1.97 */
  w33 = 1.9700000000000000e+00;
  /* #49: @34 = (@33*@10) */
  w34  = (w33*w10);
  /* #50: @34 = (@5-@34) */
  w34  = (w5-w34);
  /* #51: @35 = atan2(@34,@23) */
  w35  = atan2(w34,w23);
  /* #52: @32 = (@32-@35) */
  w32 -= w35;
  /* #53: @32 = (@30*@32) */
  w32  = (w30*w32);
  /* #54: @35 = atan(@32) */
  w35 = atan( w32 );
  /* #55: @35 = (@29*@35) */
  w35  = (w29*w35);
  /* #56: @36 = sin(@35) */
  w36 = sin( w35 );
  /* #57: @36 = (@28*@36) */
  w36  = (w28*w36);
  /* #58: @37 = sin(@14) */
  w37 = sin( w14 );
  /* #59: @38 = (@36*@37) */
  w38  = (w36*w37);
  /* #60: @16 = (@16-@38) */
  w16 -= w38;
  /* #61: @38 = 2283.36 */
  w38 = 2.2833600000000001e+03;
  /* #62: @16 = (@16/@38) */
  w16 /= w38;
  /* #63: @38 = (@5*@10) */
  w38  = (w5*w10);
  /* #64: @16 = (@16+@38) */
  w16 += w38;
  /* #65: @38 = cos(@12) */
  w38 = cos( w12 );
  /* #66: @39 = (@26*@38) */
  w39  = (w26*w38);
  /* #67: @40 = sin(@14) */
  w40 = sin( w14 );
  /* #68: @41 = (@11*@40) */
  w41  = (w11*w40);
  /* #69: @39 = (@39+@41) */
  w39 += w41;
  /* #70: @41 = cos(@14) */
  w41 = cos( w14 );
  /* #71: @42 = (@36*@41) */
  w42  = (w36*w41);
  /* #72: @39 = (@39+@42) */
  w39 += w42;
  /* #73: @42 = 2283.36 */
  w42 = 2.2833600000000001e+03;
  /* #74: @39 = (@39/@42) */
  w39 /= w42;
  /* #75: @42 = (@1*@10) */
  w42  = (w1*w10);
  /* #76: @39 = (@39-@42) */
  w39 -= w42;
  /* #77: @42 = 0.985 */
  w42 = 9.8499999999999999e-01;
  /* #78: @43 = (@42*@26) */
  w43  = (w42*w26);
  /* #79: @44 = cos(@12) */
  w44 = cos( w12 );
  /* #80: @45 = (@43*@44) */
  w45  = (w43*w44);
  /* #81: @46 = 1.97 */
  w46 = 1.9700000000000000e+00;
  /* #82: @47 = (@46*@11) */
  w47  = (w46*w11);
  /* #83: @48 = sin(@14) */
  w48 = sin( w14 );
  /* #84: @49 = (@47*@48) */
  w49  = (w47*w48);
  /* #85: @45 = (@45-@49) */
  w45 -= w49;
  /* #86: @49 = 1.97 */
  w49 = 1.9700000000000000e+00;
  /* #87: @50 = (@49*@36) */
  w50  = (w49*w36);
  /* #88: @51 = cos(@14) */
  w51 = cos( w14 );
  /* #89: @52 = (@50*@51) */
  w52  = (w50*w51);
  /* #90: @45 = (@45-@52) */
  w45 -= w52;
  /* #91: @52 = 4650 */
  w52 = 4650.;
  /* #92: @45 = (@45/@52) */
  w45 /= w52;
  /* #93: @52 = input[3][0] */
  w52 = arg[3] ? arg[3][0] : 0;
  /* #94: @53 = 0 */
  w53 = 0.;
  /* #95: @54 = vertcat(@4, @8, @10, @16, @39, @45, @52, @53) */
  rr=w54;
  *rr++ = w4;
  *rr++ = w8;
  *rr++ = w10;
  *rr++ = w16;
  *rr++ = w39;
  *rr++ = w45;
  *rr++ = w52;
  *rr++ = w53;
  /* #96: @54 = (@0*@54) */
  for (i=0, rr=w54, cs=w54; i<8; ++i) (*rr++)  = (w0*(*cs++));
  /* #97: output[0][0] = @54 */
  casadi_copy(w54, 8, res[0]);
  /* #98: @55 = input[1][0] */
  casadi_copy(arg[1], 64, w55);
  /* #99: {@54, @56, @57, @58, @59, @60, @61, @62} = horzsplit(@55) */
  casadi_copy(w55, 8, w54);
  casadi_copy(w55+8, 8, w56);
  casadi_copy(w55+16, 8, w57);
  casadi_copy(w55+24, 8, w58);
  casadi_copy(w55+32, 8, w59);
  casadi_copy(w55+40, 8, w60);
  casadi_copy(w55+48, 8, w61);
  casadi_copy(w55+56, 8, w62);
  /* #100: {NULL, NULL, @4, @8, @16, @39, @45, @52} = vertsplit(@54) */
  w4 = w54[2];
  w8 = w54[3];
  w16 = w54[4];
  w39 = w54[5];
  w45 = w54[6];
  w52 = w54[7];
  /* #101: @53 = (@3*@8) */
  w53  = (w3*w8);
  /* #102: @63 = sin(@2) */
  w63 = sin( w2 );
  /* #103: @64 = (@63*@4) */
  w64  = (w63*w4);
  /* #104: @64 = (@1*@64) */
  w64  = (w1*w64);
  /* #105: @53 = (@53-@64) */
  w53 -= w64;
  /* #106: @64 = (@6*@16) */
  w64  = (w6*w16);
  /* #107: @65 = cos(@2) */
  w65 = cos( w2 );
  /* #108: @66 = (@65*@4) */
  w66  = (w65*w4);
  /* #109: @66 = (@5*@66) */
  w66  = (w5*w66);
  /* #110: @64 = (@64+@66) */
  w64 += w66;
  /* #111: @53 = (@53-@64) */
  w53 -= w64;
  /* #112: @64 = (@7*@8) */
  w64  = (w7*w8);
  /* #113: @66 = cos(@2) */
  w66 = cos( w2 );
  /* #114: @67 = (@66*@4) */
  w67  = (w66*w4);
  /* #115: @67 = (@1*@67) */
  w67  = (w1*w67);
  /* #116: @64 = (@64+@67) */
  w64 += w67;
  /* #117: @67 = (@9*@16) */
  w67  = (w9*w16);
  /* #118: @68 = sin(@2) */
  w68 = sin( w2 );
  /* #119: @4 = (@68*@4) */
  w4  = (w68*w4);
  /* #120: @4 = (@5*@4) */
  w4  = (w5*w4);
  /* #121: @67 = (@67-@4) */
  w67 -= w4;
  /* #122: @64 = (@64+@67) */
  w64 += w67;
  /* #123: @67 = 0.000437951 */
  w67 = 4.3795108962231094e-04;
  /* #124: @4 = 2.71186 */
  w4 = 2.7118644067796609e+00;
  /* #125: @52 = (@4*@52) */
  w52  = (w4*w52);
  /* #126: @69 = (@15*@52) */
  w69  = (w15*w52);
  /* #127: @70 = sin(@14) */
  w70 = sin( w14 );
  /* #128: @71 = (@13*@45) */
  w71  = (w13*w45);
  /* #129: @72 = 00 */
  /* #130: @73 = jac_mapping(@1, @72) */
  arg1[0]=(&w1);
  arg1[1]=0;
  res1[0]=(&w73);
  if (casadi_f3(arg1, res1, iw, w, 0)) return 1;
  /* #131: {NULL, NULL, @74, @75, @76, @77, @78, @79} = vertsplit(@56) */
  w74 = w56[2];
  w75 = w56[3];
  w76 = w56[4];
  w77 = w56[5];
  w78 = w56[6];
  w79 = w56[7];
  /* #132: {NULL, NULL, @80, @81, @82, @83, @84, @85} = vertsplit(@57) */
  w80 = w57[2];
  w81 = w57[3];
  w82 = w57[4];
  w83 = w57[5];
  w84 = w57[6];
  w85 = w57[7];
  /* #133: {NULL, NULL, @86, @87, @88, @89, @90, @91} = vertsplit(@58) */
  w86 = w58[2];
  w87 = w58[3];
  w88 = w58[4];
  w89 = w58[5];
  w90 = w58[6];
  w91 = w58[7];
  /* #134: {NULL, NULL, @92, @93, @94, @95, @96, @97} = vertsplit(@59) */
  w92 = w59[2];
  w93 = w59[3];
  w94 = w59[4];
  w95 = w59[5];
  w96 = w59[6];
  w97 = w59[7];
  /* #135: {NULL, NULL, @98, @99, @100, @101, @102, @103} = vertsplit(@60) */
  w98 = w60[2];
  w99 = w60[3];
  w100 = w60[4];
  w101 = w60[5];
  w102 = w60[6];
  w103 = w60[7];
  /* #136: {NULL, NULL, @104, @105, @106, @107, @108, @109} = vertsplit(@61) */
  w104 = w61[2];
  w105 = w61[3];
  w106 = w61[4];
  w107 = w61[5];
  w108 = w61[6];
  w109 = w61[7];
  /* #137: {NULL, NULL, @110, @111, @112, @113, @114, @115} = vertsplit(@62) */
  w110 = w62[2];
  w111 = w62[3];
  w112 = w62[4];
  w113 = w62[5];
  w114 = w62[6];
  w115 = w62[7];
  /* #138: @62 = horzcat(@8, @75, @81, @87, @93, @99, @105, @111) */
  rr=w62;
  *rr++ = w8;
  *rr++ = w75;
  *rr++ = w81;
  *rr++ = w87;
  *rr++ = w93;
  *rr++ = w99;
  *rr++ = w105;
  *rr++ = w111;
  /* #139: @62 = (@73*@62) */
  for (i=0, rr=w62, cs=w62; i<8; ++i) (*rr++)  = (w73*(*cs++));
  /* #140: {@73, @116, @117, @118, @119, @120, @121, @122} = horzsplit(@62) */
  w73 = w62[0];
  w116 = w62[1];
  w117 = w62[2];
  w118 = w62[3];
  w119 = w62[4];
  w120 = w62[5];
  w121 = w62[6];
  w122 = w62[7];
  /* #141: @73 = (@12*@73) */
  w73  = (w12*w73);
  /* #142: @71 = (@71+@73) */
  w71 += w73;
  /* #143: @73 = (@70*@71) */
  w73  = (w70*w71);
  /* #144: @73 = (@11*@73) */
  w73  = (w11*w73);
  /* #145: @69 = (@69-@73) */
  w69 -= w73;
  /* #146: @73 = cos(@25) */
  w73 = cos( w25 );
  /* #147: @123 = sq(@21) */
  w123 = casadi_sq( w21 );
  /* #148: @124 = sq(@23) */
  w124 = casadi_sq( w23 );
  /* #149: @123 = (@123+@124) */
  w123 += w124;
  /* #150: @124 = (@23/@123) */
  w124  = (w23/w123);
  /* #151: @125 = (@20*@39) */
  w125  = (w20*w39);
  /* #152: @125 = (@16+@125) */
  w125  = (w16+w125);
  /* #153: @125 = (@124*@125) */
  w125  = (w124*w125);
  /* #154: @123 = (@21/@123) */
  w123  = (w21/w123);
  /* #155: @126 = (@22<=@1) */
  w126  = (w22<=w1);
  /* #156: @127 = (@1<=@22) */
  w127  = (w1<=w22);
  /* #157: @127 = (@126+@127) */
  w127  = (w126+w127);
  /* #158: @126 = (@126/@127) */
  w126 /= w127;
  /* #159: @127 = (@126*@8) */
  w127  = (w126*w8);
  /* #160: @128 = (@123*@127) */
  w128  = (w123*w127);
  /* #161: @125 = (@125-@128) */
  w125 -= w128;
  /* #162: @125 = (@45-@125) */
  w125  = (w45-w125);
  /* #163: @125 = (@19*@125) */
  w125  = (w19*w125);
  /* #164: @128 = 1 */
  w128 = 1.;
  /* #165: @129 = sq(@24) */
  w129 = casadi_sq( w24 );
  /* #166: @128 = (@128+@129) */
  w128 += w129;
  /* #167: @125 = (@125/@128) */
  w125 /= w128;
  /* #168: @125 = (@18*@125) */
  w125  = (w18*w125);
  /* #169: @125 = (@73*@125) */
  w125  = (w73*w125);
  /* #170: @125 = (@17*@125) */
  w125  = (w17*w125);
  /* #171: @129 = (@27*@125) */
  w129  = (w27*w125);
  /* #172: @130 = cos(@12) */
  w130 = cos( w12 );
  /* #173: @131 = (@130*@45) */
  w131  = (w130*w45);
  /* #174: @131 = (@26*@131) */
  w131  = (w26*w131);
  /* #175: @129 = (@129+@131) */
  w129 += w131;
  /* #176: @69 = (@69-@129) */
  w69 -= w129;
  /* #177: @129 = cos(@35) */
  w129 = cos( w35 );
  /* #178: @131 = (@31*@45) */
  w131  = (w31*w45);
  /* #179: @72 = 00 */
  /* #180: @132 = jac_mapping(@1, @72) */
  arg1[0]=(&w1);
  arg1[1]=0;
  res1[0]=(&w132);
  if (casadi_f4(arg1, res1, iw, w, 0)) return 1;
  /* #181: @62 = horzcat(@8, @75, @81, @87, @93, @99, @105, @111) */
  rr=w62;
  *rr++ = w8;
  *rr++ = w75;
  *rr++ = w81;
  *rr++ = w87;
  *rr++ = w93;
  *rr++ = w99;
  *rr++ = w105;
  *rr++ = w111;
  /* #182: @62 = (@132*@62) */
  for (i=0, rr=w62, cs=w62; i<8; ++i) (*rr++)  = (w132*(*cs++));
  /* #183: {@132, @133, @134, @135, @136, @137, @138, @139} = horzsplit(@62) */
  w132 = w62[0];
  w133 = w62[1];
  w134 = w62[2];
  w135 = w62[3];
  w136 = w62[4];
  w137 = w62[5];
  w138 = w62[6];
  w139 = w62[7];
  /* #184: @132 = (@12*@132) */
  w132  = (w12*w132);
  /* #185: @131 = (@131+@132) */
  w131 += w132;
  /* #186: @132 = sq(@34) */
  w132 = casadi_sq( w34 );
  /* #187: @140 = sq(@23) */
  w140 = casadi_sq( w23 );
  /* #188: @132 = (@132+@140) */
  w132 += w140;
  /* #189: @140 = (@23/@132) */
  w140  = (w23/w132);
  /* #190: @141 = (@33*@39) */
  w141  = (w33*w39);
  /* #191: @141 = (@16-@141) */
  w141  = (w16-w141);
  /* #192: @141 = (@140*@141) */
  w141  = (w140*w141);
  /* #193: @132 = (@34/@132) */
  w132  = (w34/w132);
  /* #194: @127 = (@132*@127) */
  w127  = (w132*w127);
  /* #195: @141 = (@141-@127) */
  w141 -= w127;
  /* #196: @131 = (@131-@141) */
  w131 -= w141;
  /* #197: @131 = (@30*@131) */
  w131  = (w30*w131);
  /* #198: @141 = 1 */
  w141 = 1.;
  /* #199: @127 = sq(@32) */
  w127 = casadi_sq( w32 );
  /* #200: @141 = (@141+@127) */
  w141 += w127;
  /* #201: @131 = (@131/@141) */
  w131 /= w141;
  /* #202: @131 = (@29*@131) */
  w131  = (w29*w131);
  /* #203: @131 = (@129*@131) */
  w131  = (w129*w131);
  /* #204: @131 = (@28*@131) */
  w131  = (w28*w131);
  /* #205: @127 = (@37*@131) */
  w127  = (w37*w131);
  /* #206: @142 = cos(@14) */
  w142 = cos( w14 );
  /* #207: @143 = (@142*@71) */
  w143  = (w142*w71);
  /* #208: @143 = (@36*@143) */
  w143  = (w36*w143);
  /* #209: @127 = (@127+@143) */
  w127 += w143;
  /* #210: @69 = (@69-@127) */
  w69 -= w127;
  /* #211: @69 = (@67*@69) */
  w69  = (w67*w69);
  /* #212: @16 = (@10*@16) */
  w16  = (w10*w16);
  /* #213: @127 = (@5*@39) */
  w127  = (w5*w39);
  /* #214: @16 = (@16+@127) */
  w16 += w127;
  /* #215: @69 = (@69+@16) */
  w69 += w16;
  /* #216: @16 = 0.000437951 */
  w16 = 4.3795108962231094e-04;
  /* #217: @127 = (@38*@125) */
  w127  = (w38*w125);
  /* #218: @143 = sin(@12) */
  w143 = sin( w12 );
  /* #219: @144 = (@143*@45) */
  w144  = (w143*w45);
  /* #220: @144 = (@26*@144) */
  w144  = (w26*w144);
  /* #221: @127 = (@127-@144) */
  w127 -= w144;
  /* #222: @144 = (@40*@52) */
  w144  = (w40*w52);
  /* #223: @145 = cos(@14) */
  w145 = cos( w14 );
  /* #224: @146 = (@145*@71) */
  w146  = (w145*w71);
  /* #225: @146 = (@11*@146) */
  w146  = (w11*w146);
  /* #226: @144 = (@144+@146) */
  w144 += w146;
  /* #227: @127 = (@127+@144) */
  w127 += w144;
  /* #228: @144 = (@41*@131) */
  w144  = (w41*w131);
  /* #229: @146 = sin(@14) */
  w146 = sin( w14 );
  /* #230: @147 = (@146*@71) */
  w147  = (w146*w71);
  /* #231: @147 = (@36*@147) */
  w147  = (w36*w147);
  /* #232: @144 = (@144-@147) */
  w144 -= w147;
  /* #233: @127 = (@127+@144) */
  w127 += w144;
  /* #234: @127 = (@16*@127) */
  w127  = (w16*w127);
  /* #235: @8 = (@10*@8) */
  w8  = (w10*w8);
  /* #236: @144 = (@1*@39) */
  w144  = (w1*w39);
  /* #237: @8 = (@8+@144) */
  w8 += w144;
  /* #238: @127 = (@127-@8) */
  w127 -= w8;
  /* #239: @8 = 0.000215054 */
  w8 = 2.1505376344086021e-04;
  /* #240: @125 = (@42*@125) */
  w125  = (w42*w125);
  /* #241: @125 = (@44*@125) */
  w125  = (w44*w125);
  /* #242: @144 = sin(@12) */
  w144 = sin( w12 );
  /* #243: @45 = (@144*@45) */
  w45  = (w144*w45);
  /* #244: @45 = (@43*@45) */
  w45  = (w43*w45);
  /* #245: @125 = (@125-@45) */
  w125 -= w45;
  /* #246: @52 = (@46*@52) */
  w52  = (w46*w52);
  /* #247: @52 = (@48*@52) */
  w52  = (w48*w52);
  /* #248: @45 = cos(@14) */
  w45 = cos( w14 );
  /* #249: @147 = (@45*@71) */
  w147  = (w45*w71);
  /* #250: @147 = (@47*@147) */
  w147  = (w47*w147);
  /* #251: @52 = (@52+@147) */
  w52 += w147;
  /* #252: @125 = (@125-@52) */
  w125 -= w52;
  /* #253: @131 = (@49*@131) */
  w131  = (w49*w131);
  /* #254: @131 = (@51*@131) */
  w131  = (w51*w131);
  /* #255: @52 = sin(@14) */
  w52 = sin( w14 );
  /* #256: @71 = (@52*@71) */
  w71  = (w52*w71);
  /* #257: @71 = (@50*@71) */
  w71  = (w50*w71);
  /* #258: @131 = (@131-@71) */
  w131 -= w71;
  /* #259: @125 = (@125-@131) */
  w125 -= w131;
  /* #260: @125 = (@8*@125) */
  w125  = (w8*w125);
  /* #261: @72 = 00 */
  /* #262: @148 = 00 */
  /* #263: @149 = vertcat(@53, @64, @39, @69, @127, @125, @72, @148) */
  rr=w149;
  *rr++ = w53;
  *rr++ = w64;
  *rr++ = w39;
  *rr++ = w69;
  *rr++ = w127;
  *rr++ = w125;
  /* #264: @149 = (@0*@149) */
  for (i=0, rr=w149, cs=w149; i<6; ++i) (*rr++)  = (w0*(*cs++));
  /* #265: output[1][0] = @149 */
  casadi_copy(w149, 6, res[1]);
  /* #266: @53 = (@3*@75) */
  w53  = (w3*w75);
  /* #267: @64 = (@63*@74) */
  w64  = (w63*w74);
  /* #268: @64 = (@1*@64) */
  w64  = (w1*w64);
  /* #269: @53 = (@53-@64) */
  w53 -= w64;
  /* #270: @64 = (@6*@76) */
  w64  = (w6*w76);
  /* #271: @39 = (@65*@74) */
  w39  = (w65*w74);
  /* #272: @39 = (@5*@39) */
  w39  = (w5*w39);
  /* #273: @64 = (@64+@39) */
  w64 += w39;
  /* #274: @53 = (@53-@64) */
  w53 -= w64;
  /* #275: @64 = (@7*@75) */
  w64  = (w7*w75);
  /* #276: @39 = (@66*@74) */
  w39  = (w66*w74);
  /* #277: @39 = (@1*@39) */
  w39  = (w1*w39);
  /* #278: @64 = (@64+@39) */
  w64 += w39;
  /* #279: @39 = (@9*@76) */
  w39  = (w9*w76);
  /* #280: @74 = (@68*@74) */
  w74  = (w68*w74);
  /* #281: @74 = (@5*@74) */
  w74  = (w5*w74);
  /* #282: @39 = (@39-@74) */
  w39 -= w74;
  /* #283: @64 = (@64+@39) */
  w64 += w39;
  /* #284: @79 = (@4*@79) */
  w79  = (w4*w79);
  /* #285: @39 = (@15*@79) */
  w39  = (w15*w79);
  /* #286: @74 = (@13*@78) */
  w74  = (w13*w78);
  /* #287: @116 = (@12*@116) */
  w116  = (w12*w116);
  /* #288: @74 = (@74+@116) */
  w74 += w116;
  /* #289: @116 = (@70*@74) */
  w116  = (w70*w74);
  /* #290: @116 = (@11*@116) */
  w116  = (w11*w116);
  /* #291: @39 = (@39-@116) */
  w39 -= w116;
  /* #292: @116 = (@20*@77) */
  w116  = (w20*w77);
  /* #293: @116 = (@76+@116) */
  w116  = (w76+w116);
  /* #294: @116 = (@124*@116) */
  w116  = (w124*w116);
  /* #295: @69 = (@126*@75) */
  w69  = (w126*w75);
  /* #296: @127 = (@123*@69) */
  w127  = (w123*w69);
  /* #297: @116 = (@116-@127) */
  w116 -= w127;
  /* #298: @116 = (@78-@116) */
  w116  = (w78-w116);
  /* #299: @116 = (@19*@116) */
  w116  = (w19*w116);
  /* #300: @116 = (@116/@128) */
  w116 /= w128;
  /* #301: @116 = (@18*@116) */
  w116  = (w18*w116);
  /* #302: @116 = (@73*@116) */
  w116  = (w73*w116);
  /* #303: @116 = (@17*@116) */
  w116  = (w17*w116);
  /* #304: @127 = (@27*@116) */
  w127  = (w27*w116);
  /* #305: @125 = (@130*@78) */
  w125  = (w130*w78);
  /* #306: @125 = (@26*@125) */
  w125  = (w26*w125);
  /* #307: @127 = (@127+@125) */
  w127 += w125;
  /* #308: @39 = (@39-@127) */
  w39 -= w127;
  /* #309: @127 = (@31*@78) */
  w127  = (w31*w78);
  /* #310: @133 = (@12*@133) */
  w133  = (w12*w133);
  /* #311: @127 = (@127+@133) */
  w127 += w133;
  /* #312: @133 = (@33*@77) */
  w133  = (w33*w77);
  /* #313: @133 = (@76-@133) */
  w133  = (w76-w133);
  /* #314: @133 = (@140*@133) */
  w133  = (w140*w133);
  /* #315: @69 = (@132*@69) */
  w69  = (w132*w69);
  /* #316: @133 = (@133-@69) */
  w133 -= w69;
  /* #317: @127 = (@127-@133) */
  w127 -= w133;
  /* #318: @127 = (@30*@127) */
  w127  = (w30*w127);
  /* #319: @127 = (@127/@141) */
  w127 /= w141;
  /* #320: @127 = (@29*@127) */
  w127  = (w29*w127);
  /* #321: @127 = (@129*@127) */
  w127  = (w129*w127);
  /* #322: @127 = (@28*@127) */
  w127  = (w28*w127);
  /* #323: @133 = (@37*@127) */
  w133  = (w37*w127);
  /* #324: @69 = (@142*@74) */
  w69  = (w142*w74);
  /* #325: @69 = (@36*@69) */
  w69  = (w36*w69);
  /* #326: @133 = (@133+@69) */
  w133 += w69;
  /* #327: @39 = (@39-@133) */
  w39 -= w133;
  /* #328: @39 = (@67*@39) */
  w39  = (w67*w39);
  /* #329: @76 = (@10*@76) */
  w76  = (w10*w76);
  /* #330: @133 = (@5*@77) */
  w133  = (w5*w77);
  /* #331: @76 = (@76+@133) */
  w76 += w133;
  /* #332: @39 = (@39+@76) */
  w39 += w76;
  /* #333: @76 = (@38*@116) */
  w76  = (w38*w116);
  /* #334: @133 = (@143*@78) */
  w133  = (w143*w78);
  /* #335: @133 = (@26*@133) */
  w133  = (w26*w133);
  /* #336: @76 = (@76-@133) */
  w76 -= w133;
  /* #337: @133 = (@40*@79) */
  w133  = (w40*w79);
  /* #338: @69 = (@145*@74) */
  w69  = (w145*w74);
  /* #339: @69 = (@11*@69) */
  w69  = (w11*w69);
  /* #340: @133 = (@133+@69) */
  w133 += w69;
  /* #341: @76 = (@76+@133) */
  w76 += w133;
  /* #342: @133 = (@41*@127) */
  w133  = (w41*w127);
  /* #343: @69 = (@146*@74) */
  w69  = (w146*w74);
  /* #344: @69 = (@36*@69) */
  w69  = (w36*w69);
  /* #345: @133 = (@133-@69) */
  w133 -= w69;
  /* #346: @76 = (@76+@133) */
  w76 += w133;
  /* #347: @76 = (@16*@76) */
  w76  = (w16*w76);
  /* #348: @75 = (@10*@75) */
  w75  = (w10*w75);
  /* #349: @133 = (@1*@77) */
  w133  = (w1*w77);
  /* #350: @75 = (@75+@133) */
  w75 += w133;
  /* #351: @76 = (@76-@75) */
  w76 -= w75;
  /* #352: @116 = (@42*@116) */
  w116  = (w42*w116);
  /* #353: @116 = (@44*@116) */
  w116  = (w44*w116);
  /* #354: @78 = (@144*@78) */
  w78  = (w144*w78);
  /* #355: @78 = (@43*@78) */
  w78  = (w43*w78);
  /* #356: @116 = (@116-@78) */
  w116 -= w78;
  /* #357: @79 = (@46*@79) */
  w79  = (w46*w79);
  /* #358: @79 = (@48*@79) */
  w79  = (w48*w79);
  /* #359: @78 = (@45*@74) */
  w78  = (w45*w74);
  /* #360: @78 = (@47*@78) */
  w78  = (w47*w78);
  /* #361: @79 = (@79+@78) */
  w79 += w78;
  /* #362: @116 = (@116-@79) */
  w116 -= w79;
  /* #363: @127 = (@49*@127) */
  w127  = (w49*w127);
  /* #364: @127 = (@51*@127) */
  w127  = (w51*w127);
  /* #365: @74 = (@52*@74) */
  w74  = (w52*w74);
  /* #366: @74 = (@50*@74) */
  w74  = (w50*w74);
  /* #367: @127 = (@127-@74) */
  w127 -= w74;
  /* #368: @116 = (@116-@127) */
  w116 -= w127;
  /* #369: @116 = (@8*@116) */
  w116  = (w8*w116);
  /* #370: @72 = 00 */
  /* #371: @148 = 00 */
  /* #372: @149 = vertcat(@53, @64, @77, @39, @76, @116, @72, @148) */
  rr=w149;
  *rr++ = w53;
  *rr++ = w64;
  *rr++ = w77;
  *rr++ = w39;
  *rr++ = w76;
  *rr++ = w116;
  /* #373: @149 = (@0*@149) */
  for (i=0, rr=w149, cs=w149; i<6; ++i) (*rr++)  = (w0*(*cs++));
  /* #374: output[1][1] = @149 */
  if (res[1]) casadi_copy(w149, 6, res[1]+6);
  /* #375: @53 = (@3*@81) */
  w53  = (w3*w81);
  /* #376: @64 = (@63*@80) */
  w64  = (w63*w80);
  /* #377: @64 = (@1*@64) */
  w64  = (w1*w64);
  /* #378: @53 = (@53-@64) */
  w53 -= w64;
  /* #379: @64 = (@6*@82) */
  w64  = (w6*w82);
  /* #380: @77 = (@65*@80) */
  w77  = (w65*w80);
  /* #381: @77 = (@5*@77) */
  w77  = (w5*w77);
  /* #382: @64 = (@64+@77) */
  w64 += w77;
  /* #383: @53 = (@53-@64) */
  w53 -= w64;
  /* #384: @64 = (@7*@81) */
  w64  = (w7*w81);
  /* #385: @77 = (@66*@80) */
  w77  = (w66*w80);
  /* #386: @77 = (@1*@77) */
  w77  = (w1*w77);
  /* #387: @64 = (@64+@77) */
  w64 += w77;
  /* #388: @77 = (@9*@82) */
  w77  = (w9*w82);
  /* #389: @80 = (@68*@80) */
  w80  = (w68*w80);
  /* #390: @80 = (@5*@80) */
  w80  = (w5*w80);
  /* #391: @77 = (@77-@80) */
  w77 -= w80;
  /* #392: @64 = (@64+@77) */
  w64 += w77;
  /* #393: @85 = (@4*@85) */
  w85  = (w4*w85);
  /* #394: @77 = (@15*@85) */
  w77  = (w15*w85);
  /* #395: @80 = (@13*@84) */
  w80  = (w13*w84);
  /* #396: @117 = (@12*@117) */
  w117  = (w12*w117);
  /* #397: @80 = (@80+@117) */
  w80 += w117;
  /* #398: @117 = (@70*@80) */
  w117  = (w70*w80);
  /* #399: @117 = (@11*@117) */
  w117  = (w11*w117);
  /* #400: @77 = (@77-@117) */
  w77 -= w117;
  /* #401: @117 = (@20*@83) */
  w117  = (w20*w83);
  /* #402: @117 = (@82+@117) */
  w117  = (w82+w117);
  /* #403: @117 = (@124*@117) */
  w117  = (w124*w117);
  /* #404: @39 = (@126*@81) */
  w39  = (w126*w81);
  /* #405: @76 = (@123*@39) */
  w76  = (w123*w39);
  /* #406: @117 = (@117-@76) */
  w117 -= w76;
  /* #407: @117 = (@84-@117) */
  w117  = (w84-w117);
  /* #408: @117 = (@19*@117) */
  w117  = (w19*w117);
  /* #409: @117 = (@117/@128) */
  w117 /= w128;
  /* #410: @117 = (@18*@117) */
  w117  = (w18*w117);
  /* #411: @117 = (@73*@117) */
  w117  = (w73*w117);
  /* #412: @117 = (@17*@117) */
  w117  = (w17*w117);
  /* #413: @76 = (@27*@117) */
  w76  = (w27*w117);
  /* #414: @116 = (@130*@84) */
  w116  = (w130*w84);
  /* #415: @116 = (@26*@116) */
  w116  = (w26*w116);
  /* #416: @76 = (@76+@116) */
  w76 += w116;
  /* #417: @77 = (@77-@76) */
  w77 -= w76;
  /* #418: @76 = (@31*@84) */
  w76  = (w31*w84);
  /* #419: @134 = (@12*@134) */
  w134  = (w12*w134);
  /* #420: @76 = (@76+@134) */
  w76 += w134;
  /* #421: @134 = (@33*@83) */
  w134  = (w33*w83);
  /* #422: @134 = (@82-@134) */
  w134  = (w82-w134);
  /* #423: @134 = (@140*@134) */
  w134  = (w140*w134);
  /* #424: @39 = (@132*@39) */
  w39  = (w132*w39);
  /* #425: @134 = (@134-@39) */
  w134 -= w39;
  /* #426: @76 = (@76-@134) */
  w76 -= w134;
  /* #427: @76 = (@30*@76) */
  w76  = (w30*w76);
  /* #428: @76 = (@76/@141) */
  w76 /= w141;
  /* #429: @76 = (@29*@76) */
  w76  = (w29*w76);
  /* #430: @76 = (@129*@76) */
  w76  = (w129*w76);
  /* #431: @76 = (@28*@76) */
  w76  = (w28*w76);
  /* #432: @134 = (@37*@76) */
  w134  = (w37*w76);
  /* #433: @39 = (@142*@80) */
  w39  = (w142*w80);
  /* #434: @39 = (@36*@39) */
  w39  = (w36*w39);
  /* #435: @134 = (@134+@39) */
  w134 += w39;
  /* #436: @77 = (@77-@134) */
  w77 -= w134;
  /* #437: @77 = (@67*@77) */
  w77  = (w67*w77);
  /* #438: @82 = (@10*@82) */
  w82  = (w10*w82);
  /* #439: @134 = (@5*@83) */
  w134  = (w5*w83);
  /* #440: @82 = (@82+@134) */
  w82 += w134;
  /* #441: @77 = (@77+@82) */
  w77 += w82;
  /* #442: @82 = (@38*@117) */
  w82  = (w38*w117);
  /* #443: @134 = (@143*@84) */
  w134  = (w143*w84);
  /* #444: @134 = (@26*@134) */
  w134  = (w26*w134);
  /* #445: @82 = (@82-@134) */
  w82 -= w134;
  /* #446: @134 = (@40*@85) */
  w134  = (w40*w85);
  /* #447: @39 = (@145*@80) */
  w39  = (w145*w80);
  /* #448: @39 = (@11*@39) */
  w39  = (w11*w39);
  /* #449: @134 = (@134+@39) */
  w134 += w39;
  /* #450: @82 = (@82+@134) */
  w82 += w134;
  /* #451: @134 = (@41*@76) */
  w134  = (w41*w76);
  /* #452: @39 = (@146*@80) */
  w39  = (w146*w80);
  /* #453: @39 = (@36*@39) */
  w39  = (w36*w39);
  /* #454: @134 = (@134-@39) */
  w134 -= w39;
  /* #455: @82 = (@82+@134) */
  w82 += w134;
  /* #456: @82 = (@16*@82) */
  w82  = (w16*w82);
  /* #457: @81 = (@10*@81) */
  w81  = (w10*w81);
  /* #458: @134 = (@1*@83) */
  w134  = (w1*w83);
  /* #459: @81 = (@81+@134) */
  w81 += w134;
  /* #460: @82 = (@82-@81) */
  w82 -= w81;
  /* #461: @117 = (@42*@117) */
  w117  = (w42*w117);
  /* #462: @117 = (@44*@117) */
  w117  = (w44*w117);
  /* #463: @84 = (@144*@84) */
  w84  = (w144*w84);
  /* #464: @84 = (@43*@84) */
  w84  = (w43*w84);
  /* #465: @117 = (@117-@84) */
  w117 -= w84;
  /* #466: @85 = (@46*@85) */
  w85  = (w46*w85);
  /* #467: @85 = (@48*@85) */
  w85  = (w48*w85);
  /* #468: @84 = (@45*@80) */
  w84  = (w45*w80);
  /* #469: @84 = (@47*@84) */
  w84  = (w47*w84);
  /* #470: @85 = (@85+@84) */
  w85 += w84;
  /* #471: @117 = (@117-@85) */
  w117 -= w85;
  /* #472: @76 = (@49*@76) */
  w76  = (w49*w76);
  /* #473: @76 = (@51*@76) */
  w76  = (w51*w76);
  /* #474: @80 = (@52*@80) */
  w80  = (w52*w80);
  /* #475: @80 = (@50*@80) */
  w80  = (w50*w80);
  /* #476: @76 = (@76-@80) */
  w76 -= w80;
  /* #477: @117 = (@117-@76) */
  w117 -= w76;
  /* #478: @117 = (@8*@117) */
  w117  = (w8*w117);
  /* #479: @72 = 00 */
  /* #480: @148 = 00 */
  /* #481: @149 = vertcat(@53, @64, @83, @77, @82, @117, @72, @148) */
  rr=w149;
  *rr++ = w53;
  *rr++ = w64;
  *rr++ = w83;
  *rr++ = w77;
  *rr++ = w82;
  *rr++ = w117;
  /* #482: @149 = (@0*@149) */
  for (i=0, rr=w149, cs=w149; i<6; ++i) (*rr++)  = (w0*(*cs++));
  /* #483: output[1][2] = @149 */
  if (res[1]) casadi_copy(w149, 6, res[1]+12);
  /* #484: @53 = (@3*@87) */
  w53  = (w3*w87);
  /* #485: @64 = (@63*@86) */
  w64  = (w63*w86);
  /* #486: @64 = (@1*@64) */
  w64  = (w1*w64);
  /* #487: @53 = (@53-@64) */
  w53 -= w64;
  /* #488: @64 = (@6*@88) */
  w64  = (w6*w88);
  /* #489: @83 = (@65*@86) */
  w83  = (w65*w86);
  /* #490: @83 = (@5*@83) */
  w83  = (w5*w83);
  /* #491: @64 = (@64+@83) */
  w64 += w83;
  /* #492: @53 = (@53-@64) */
  w53 -= w64;
  /* #493: @64 = (@7*@87) */
  w64  = (w7*w87);
  /* #494: @83 = (@66*@86) */
  w83  = (w66*w86);
  /* #495: @83 = (@1*@83) */
  w83  = (w1*w83);
  /* #496: @64 = (@64+@83) */
  w64 += w83;
  /* #497: @83 = (@9*@88) */
  w83  = (w9*w88);
  /* #498: @86 = (@68*@86) */
  w86  = (w68*w86);
  /* #499: @86 = (@5*@86) */
  w86  = (w5*w86);
  /* #500: @83 = (@83-@86) */
  w83 -= w86;
  /* #501: @64 = (@64+@83) */
  w64 += w83;
  /* #502: @91 = (@4*@91) */
  w91  = (w4*w91);
  /* #503: @83 = (@15*@91) */
  w83  = (w15*w91);
  /* #504: @86 = (@13*@90) */
  w86  = (w13*w90);
  /* #505: @118 = (@12*@118) */
  w118  = (w12*w118);
  /* #506: @86 = (@86+@118) */
  w86 += w118;
  /* #507: @118 = (@70*@86) */
  w118  = (w70*w86);
  /* #508: @118 = (@11*@118) */
  w118  = (w11*w118);
  /* #509: @83 = (@83-@118) */
  w83 -= w118;
  /* #510: @118 = (@20*@89) */
  w118  = (w20*w89);
  /* #511: @118 = (@88+@118) */
  w118  = (w88+w118);
  /* #512: @118 = (@124*@118) */
  w118  = (w124*w118);
  /* #513: @77 = (@126*@87) */
  w77  = (w126*w87);
  /* #514: @82 = (@123*@77) */
  w82  = (w123*w77);
  /* #515: @118 = (@118-@82) */
  w118 -= w82;
  /* #516: @118 = (@90-@118) */
  w118  = (w90-w118);
  /* #517: @118 = (@19*@118) */
  w118  = (w19*w118);
  /* #518: @118 = (@118/@128) */
  w118 /= w128;
  /* #519: @118 = (@18*@118) */
  w118  = (w18*w118);
  /* #520: @118 = (@73*@118) */
  w118  = (w73*w118);
  /* #521: @118 = (@17*@118) */
  w118  = (w17*w118);
  /* #522: @82 = (@27*@118) */
  w82  = (w27*w118);
  /* #523: @117 = (@130*@90) */
  w117  = (w130*w90);
  /* #524: @117 = (@26*@117) */
  w117  = (w26*w117);
  /* #525: @82 = (@82+@117) */
  w82 += w117;
  /* #526: @83 = (@83-@82) */
  w83 -= w82;
  /* #527: @82 = (@31*@90) */
  w82  = (w31*w90);
  /* #528: @135 = (@12*@135) */
  w135  = (w12*w135);
  /* #529: @82 = (@82+@135) */
  w82 += w135;
  /* #530: @135 = (@33*@89) */
  w135  = (w33*w89);
  /* #531: @135 = (@88-@135) */
  w135  = (w88-w135);
  /* #532: @135 = (@140*@135) */
  w135  = (w140*w135);
  /* #533: @77 = (@132*@77) */
  w77  = (w132*w77);
  /* #534: @135 = (@135-@77) */
  w135 -= w77;
  /* #535: @82 = (@82-@135) */
  w82 -= w135;
  /* #536: @82 = (@30*@82) */
  w82  = (w30*w82);
  /* #537: @82 = (@82/@141) */
  w82 /= w141;
  /* #538: @82 = (@29*@82) */
  w82  = (w29*w82);
  /* #539: @82 = (@129*@82) */
  w82  = (w129*w82);
  /* #540: @82 = (@28*@82) */
  w82  = (w28*w82);
  /* #541: @135 = (@37*@82) */
  w135  = (w37*w82);
  /* #542: @77 = (@142*@86) */
  w77  = (w142*w86);
  /* #543: @77 = (@36*@77) */
  w77  = (w36*w77);
  /* #544: @135 = (@135+@77) */
  w135 += w77;
  /* #545: @83 = (@83-@135) */
  w83 -= w135;
  /* #546: @83 = (@67*@83) */
  w83  = (w67*w83);
  /* #547: @88 = (@10*@88) */
  w88  = (w10*w88);
  /* #548: @135 = (@5*@89) */
  w135  = (w5*w89);
  /* #549: @88 = (@88+@135) */
  w88 += w135;
  /* #550: @83 = (@83+@88) */
  w83 += w88;
  /* #551: @88 = (@38*@118) */
  w88  = (w38*w118);
  /* #552: @135 = (@143*@90) */
  w135  = (w143*w90);
  /* #553: @135 = (@26*@135) */
  w135  = (w26*w135);
  /* #554: @88 = (@88-@135) */
  w88 -= w135;
  /* #555: @135 = (@40*@91) */
  w135  = (w40*w91);
  /* #556: @77 = (@145*@86) */
  w77  = (w145*w86);
  /* #557: @77 = (@11*@77) */
  w77  = (w11*w77);
  /* #558: @135 = (@135+@77) */
  w135 += w77;
  /* #559: @88 = (@88+@135) */
  w88 += w135;
  /* #560: @135 = (@41*@82) */
  w135  = (w41*w82);
  /* #561: @77 = (@146*@86) */
  w77  = (w146*w86);
  /* #562: @77 = (@36*@77) */
  w77  = (w36*w77);
  /* #563: @135 = (@135-@77) */
  w135 -= w77;
  /* #564: @88 = (@88+@135) */
  w88 += w135;
  /* #565: @88 = (@16*@88) */
  w88  = (w16*w88);
  /* #566: @87 = (@10*@87) */
  w87  = (w10*w87);
  /* #567: @135 = (@1*@89) */
  w135  = (w1*w89);
  /* #568: @87 = (@87+@135) */
  w87 += w135;
  /* #569: @88 = (@88-@87) */
  w88 -= w87;
  /* #570: @118 = (@42*@118) */
  w118  = (w42*w118);
  /* #571: @118 = (@44*@118) */
  w118  = (w44*w118);
  /* #572: @90 = (@144*@90) */
  w90  = (w144*w90);
  /* #573: @90 = (@43*@90) */
  w90  = (w43*w90);
  /* #574: @118 = (@118-@90) */
  w118 -= w90;
  /* #575: @91 = (@46*@91) */
  w91  = (w46*w91);
  /* #576: @91 = (@48*@91) */
  w91  = (w48*w91);
  /* #577: @90 = (@45*@86) */
  w90  = (w45*w86);
  /* #578: @90 = (@47*@90) */
  w90  = (w47*w90);
  /* #579: @91 = (@91+@90) */
  w91 += w90;
  /* #580: @118 = (@118-@91) */
  w118 -= w91;
  /* #581: @82 = (@49*@82) */
  w82  = (w49*w82);
  /* #582: @82 = (@51*@82) */
  w82  = (w51*w82);
  /* #583: @86 = (@52*@86) */
  w86  = (w52*w86);
  /* #584: @86 = (@50*@86) */
  w86  = (w50*w86);
  /* #585: @82 = (@82-@86) */
  w82 -= w86;
  /* #586: @118 = (@118-@82) */
  w118 -= w82;
  /* #587: @118 = (@8*@118) */
  w118  = (w8*w118);
  /* #588: @72 = 00 */
  /* #589: @148 = 00 */
  /* #590: @149 = vertcat(@53, @64, @89, @83, @88, @118, @72, @148) */
  rr=w149;
  *rr++ = w53;
  *rr++ = w64;
  *rr++ = w89;
  *rr++ = w83;
  *rr++ = w88;
  *rr++ = w118;
  /* #591: @149 = (@0*@149) */
  for (i=0, rr=w149, cs=w149; i<6; ++i) (*rr++)  = (w0*(*cs++));
  /* #592: output[1][3] = @149 */
  if (res[1]) casadi_copy(w149, 6, res[1]+18);
  /* #593: @53 = (@3*@93) */
  w53  = (w3*w93);
  /* #594: @64 = (@63*@92) */
  w64  = (w63*w92);
  /* #595: @64 = (@1*@64) */
  w64  = (w1*w64);
  /* #596: @53 = (@53-@64) */
  w53 -= w64;
  /* #597: @64 = (@6*@94) */
  w64  = (w6*w94);
  /* #598: @89 = (@65*@92) */
  w89  = (w65*w92);
  /* #599: @89 = (@5*@89) */
  w89  = (w5*w89);
  /* #600: @64 = (@64+@89) */
  w64 += w89;
  /* #601: @53 = (@53-@64) */
  w53 -= w64;
  /* #602: @64 = (@7*@93) */
  w64  = (w7*w93);
  /* #603: @89 = (@66*@92) */
  w89  = (w66*w92);
  /* #604: @89 = (@1*@89) */
  w89  = (w1*w89);
  /* #605: @64 = (@64+@89) */
  w64 += w89;
  /* #606: @89 = (@9*@94) */
  w89  = (w9*w94);
  /* #607: @92 = (@68*@92) */
  w92  = (w68*w92);
  /* #608: @92 = (@5*@92) */
  w92  = (w5*w92);
  /* #609: @89 = (@89-@92) */
  w89 -= w92;
  /* #610: @64 = (@64+@89) */
  w64 += w89;
  /* #611: @97 = (@4*@97) */
  w97  = (w4*w97);
  /* #612: @89 = (@15*@97) */
  w89  = (w15*w97);
  /* #613: @92 = (@13*@96) */
  w92  = (w13*w96);
  /* #614: @119 = (@12*@119) */
  w119  = (w12*w119);
  /* #615: @92 = (@92+@119) */
  w92 += w119;
  /* #616: @119 = (@70*@92) */
  w119  = (w70*w92);
  /* #617: @119 = (@11*@119) */
  w119  = (w11*w119);
  /* #618: @89 = (@89-@119) */
  w89 -= w119;
  /* #619: @119 = (@20*@95) */
  w119  = (w20*w95);
  /* #620: @119 = (@94+@119) */
  w119  = (w94+w119);
  /* #621: @119 = (@124*@119) */
  w119  = (w124*w119);
  /* #622: @83 = (@126*@93) */
  w83  = (w126*w93);
  /* #623: @88 = (@123*@83) */
  w88  = (w123*w83);
  /* #624: @119 = (@119-@88) */
  w119 -= w88;
  /* #625: @119 = (@96-@119) */
  w119  = (w96-w119);
  /* #626: @119 = (@19*@119) */
  w119  = (w19*w119);
  /* #627: @119 = (@119/@128) */
  w119 /= w128;
  /* #628: @119 = (@18*@119) */
  w119  = (w18*w119);
  /* #629: @119 = (@73*@119) */
  w119  = (w73*w119);
  /* #630: @119 = (@17*@119) */
  w119  = (w17*w119);
  /* #631: @88 = (@27*@119) */
  w88  = (w27*w119);
  /* #632: @118 = (@130*@96) */
  w118  = (w130*w96);
  /* #633: @118 = (@26*@118) */
  w118  = (w26*w118);
  /* #634: @88 = (@88+@118) */
  w88 += w118;
  /* #635: @89 = (@89-@88) */
  w89 -= w88;
  /* #636: @88 = (@31*@96) */
  w88  = (w31*w96);
  /* #637: @136 = (@12*@136) */
  w136  = (w12*w136);
  /* #638: @88 = (@88+@136) */
  w88 += w136;
  /* #639: @136 = (@33*@95) */
  w136  = (w33*w95);
  /* #640: @136 = (@94-@136) */
  w136  = (w94-w136);
  /* #641: @136 = (@140*@136) */
  w136  = (w140*w136);
  /* #642: @83 = (@132*@83) */
  w83  = (w132*w83);
  /* #643: @136 = (@136-@83) */
  w136 -= w83;
  /* #644: @88 = (@88-@136) */
  w88 -= w136;
  /* #645: @88 = (@30*@88) */
  w88  = (w30*w88);
  /* #646: @88 = (@88/@141) */
  w88 /= w141;
  /* #647: @88 = (@29*@88) */
  w88  = (w29*w88);
  /* #648: @88 = (@129*@88) */
  w88  = (w129*w88);
  /* #649: @88 = (@28*@88) */
  w88  = (w28*w88);
  /* #650: @136 = (@37*@88) */
  w136  = (w37*w88);
  /* #651: @83 = (@142*@92) */
  w83  = (w142*w92);
  /* #652: @83 = (@36*@83) */
  w83  = (w36*w83);
  /* #653: @136 = (@136+@83) */
  w136 += w83;
  /* #654: @89 = (@89-@136) */
  w89 -= w136;
  /* #655: @89 = (@67*@89) */
  w89  = (w67*w89);
  /* #656: @94 = (@10*@94) */
  w94  = (w10*w94);
  /* #657: @136 = (@5*@95) */
  w136  = (w5*w95);
  /* #658: @94 = (@94+@136) */
  w94 += w136;
  /* #659: @89 = (@89+@94) */
  w89 += w94;
  /* #660: @94 = (@38*@119) */
  w94  = (w38*w119);
  /* #661: @136 = (@143*@96) */
  w136  = (w143*w96);
  /* #662: @136 = (@26*@136) */
  w136  = (w26*w136);
  /* #663: @94 = (@94-@136) */
  w94 -= w136;
  /* #664: @136 = (@40*@97) */
  w136  = (w40*w97);
  /* #665: @83 = (@145*@92) */
  w83  = (w145*w92);
  /* #666: @83 = (@11*@83) */
  w83  = (w11*w83);
  /* #667: @136 = (@136+@83) */
  w136 += w83;
  /* #668: @94 = (@94+@136) */
  w94 += w136;
  /* #669: @136 = (@41*@88) */
  w136  = (w41*w88);
  /* #670: @83 = (@146*@92) */
  w83  = (w146*w92);
  /* #671: @83 = (@36*@83) */
  w83  = (w36*w83);
  /* #672: @136 = (@136-@83) */
  w136 -= w83;
  /* #673: @94 = (@94+@136) */
  w94 += w136;
  /* #674: @94 = (@16*@94) */
  w94  = (w16*w94);
  /* #675: @93 = (@10*@93) */
  w93  = (w10*w93);
  /* #676: @136 = (@1*@95) */
  w136  = (w1*w95);
  /* #677: @93 = (@93+@136) */
  w93 += w136;
  /* #678: @94 = (@94-@93) */
  w94 -= w93;
  /* #679: @119 = (@42*@119) */
  w119  = (w42*w119);
  /* #680: @119 = (@44*@119) */
  w119  = (w44*w119);
  /* #681: @96 = (@144*@96) */
  w96  = (w144*w96);
  /* #682: @96 = (@43*@96) */
  w96  = (w43*w96);
  /* #683: @119 = (@119-@96) */
  w119 -= w96;
  /* #684: @97 = (@46*@97) */
  w97  = (w46*w97);
  /* #685: @97 = (@48*@97) */
  w97  = (w48*w97);
  /* #686: @96 = (@45*@92) */
  w96  = (w45*w92);
  /* #687: @96 = (@47*@96) */
  w96  = (w47*w96);
  /* #688: @97 = (@97+@96) */
  w97 += w96;
  /* #689: @119 = (@119-@97) */
  w119 -= w97;
  /* #690: @88 = (@49*@88) */
  w88  = (w49*w88);
  /* #691: @88 = (@51*@88) */
  w88  = (w51*w88);
  /* #692: @92 = (@52*@92) */
  w92  = (w52*w92);
  /* #693: @92 = (@50*@92) */
  w92  = (w50*w92);
  /* #694: @88 = (@88-@92) */
  w88 -= w92;
  /* #695: @119 = (@119-@88) */
  w119 -= w88;
  /* #696: @119 = (@8*@119) */
  w119  = (w8*w119);
  /* #697: @72 = 00 */
  /* #698: @148 = 00 */
  /* #699: @149 = vertcat(@53, @64, @95, @89, @94, @119, @72, @148) */
  rr=w149;
  *rr++ = w53;
  *rr++ = w64;
  *rr++ = w95;
  *rr++ = w89;
  *rr++ = w94;
  *rr++ = w119;
  /* #700: @149 = (@0*@149) */
  for (i=0, rr=w149, cs=w149; i<6; ++i) (*rr++)  = (w0*(*cs++));
  /* #701: output[1][4] = @149 */
  if (res[1]) casadi_copy(w149, 6, res[1]+24);
  /* #702: @53 = (@3*@99) */
  w53  = (w3*w99);
  /* #703: @64 = (@63*@98) */
  w64  = (w63*w98);
  /* #704: @64 = (@1*@64) */
  w64  = (w1*w64);
  /* #705: @53 = (@53-@64) */
  w53 -= w64;
  /* #706: @64 = (@6*@100) */
  w64  = (w6*w100);
  /* #707: @95 = (@65*@98) */
  w95  = (w65*w98);
  /* #708: @95 = (@5*@95) */
  w95  = (w5*w95);
  /* #709: @64 = (@64+@95) */
  w64 += w95;
  /* #710: @53 = (@53-@64) */
  w53 -= w64;
  /* #711: @64 = (@7*@99) */
  w64  = (w7*w99);
  /* #712: @95 = (@66*@98) */
  w95  = (w66*w98);
  /* #713: @95 = (@1*@95) */
  w95  = (w1*w95);
  /* #714: @64 = (@64+@95) */
  w64 += w95;
  /* #715: @95 = (@9*@100) */
  w95  = (w9*w100);
  /* #716: @98 = (@68*@98) */
  w98  = (w68*w98);
  /* #717: @98 = (@5*@98) */
  w98  = (w5*w98);
  /* #718: @95 = (@95-@98) */
  w95 -= w98;
  /* #719: @64 = (@64+@95) */
  w64 += w95;
  /* #720: @103 = (@4*@103) */
  w103  = (w4*w103);
  /* #721: @95 = (@15*@103) */
  w95  = (w15*w103);
  /* #722: @98 = (@13*@102) */
  w98  = (w13*w102);
  /* #723: @120 = (@12*@120) */
  w120  = (w12*w120);
  /* #724: @98 = (@98+@120) */
  w98 += w120;
  /* #725: @120 = (@70*@98) */
  w120  = (w70*w98);
  /* #726: @120 = (@11*@120) */
  w120  = (w11*w120);
  /* #727: @95 = (@95-@120) */
  w95 -= w120;
  /* #728: @120 = (@20*@101) */
  w120  = (w20*w101);
  /* #729: @120 = (@100+@120) */
  w120  = (w100+w120);
  /* #730: @120 = (@124*@120) */
  w120  = (w124*w120);
  /* #731: @89 = (@126*@99) */
  w89  = (w126*w99);
  /* #732: @94 = (@123*@89) */
  w94  = (w123*w89);
  /* #733: @120 = (@120-@94) */
  w120 -= w94;
  /* #734: @120 = (@102-@120) */
  w120  = (w102-w120);
  /* #735: @120 = (@19*@120) */
  w120  = (w19*w120);
  /* #736: @120 = (@120/@128) */
  w120 /= w128;
  /* #737: @120 = (@18*@120) */
  w120  = (w18*w120);
  /* #738: @120 = (@73*@120) */
  w120  = (w73*w120);
  /* #739: @120 = (@17*@120) */
  w120  = (w17*w120);
  /* #740: @94 = (@27*@120) */
  w94  = (w27*w120);
  /* #741: @119 = (@130*@102) */
  w119  = (w130*w102);
  /* #742: @119 = (@26*@119) */
  w119  = (w26*w119);
  /* #743: @94 = (@94+@119) */
  w94 += w119;
  /* #744: @95 = (@95-@94) */
  w95 -= w94;
  /* #745: @94 = (@31*@102) */
  w94  = (w31*w102);
  /* #746: @137 = (@12*@137) */
  w137  = (w12*w137);
  /* #747: @94 = (@94+@137) */
  w94 += w137;
  /* #748: @137 = (@33*@101) */
  w137  = (w33*w101);
  /* #749: @137 = (@100-@137) */
  w137  = (w100-w137);
  /* #750: @137 = (@140*@137) */
  w137  = (w140*w137);
  /* #751: @89 = (@132*@89) */
  w89  = (w132*w89);
  /* #752: @137 = (@137-@89) */
  w137 -= w89;
  /* #753: @94 = (@94-@137) */
  w94 -= w137;
  /* #754: @94 = (@30*@94) */
  w94  = (w30*w94);
  /* #755: @94 = (@94/@141) */
  w94 /= w141;
  /* #756: @94 = (@29*@94) */
  w94  = (w29*w94);
  /* #757: @94 = (@129*@94) */
  w94  = (w129*w94);
  /* #758: @94 = (@28*@94) */
  w94  = (w28*w94);
  /* #759: @137 = (@37*@94) */
  w137  = (w37*w94);
  /* #760: @89 = (@142*@98) */
  w89  = (w142*w98);
  /* #761: @89 = (@36*@89) */
  w89  = (w36*w89);
  /* #762: @137 = (@137+@89) */
  w137 += w89;
  /* #763: @95 = (@95-@137) */
  w95 -= w137;
  /* #764: @95 = (@67*@95) */
  w95  = (w67*w95);
  /* #765: @100 = (@10*@100) */
  w100  = (w10*w100);
  /* #766: @137 = (@5*@101) */
  w137  = (w5*w101);
  /* #767: @100 = (@100+@137) */
  w100 += w137;
  /* #768: @95 = (@95+@100) */
  w95 += w100;
  /* #769: @100 = (@38*@120) */
  w100  = (w38*w120);
  /* #770: @137 = (@143*@102) */
  w137  = (w143*w102);
  /* #771: @137 = (@26*@137) */
  w137  = (w26*w137);
  /* #772: @100 = (@100-@137) */
  w100 -= w137;
  /* #773: @137 = (@40*@103) */
  w137  = (w40*w103);
  /* #774: @89 = (@145*@98) */
  w89  = (w145*w98);
  /* #775: @89 = (@11*@89) */
  w89  = (w11*w89);
  /* #776: @137 = (@137+@89) */
  w137 += w89;
  /* #777: @100 = (@100+@137) */
  w100 += w137;
  /* #778: @137 = (@41*@94) */
  w137  = (w41*w94);
  /* #779: @89 = (@146*@98) */
  w89  = (w146*w98);
  /* #780: @89 = (@36*@89) */
  w89  = (w36*w89);
  /* #781: @137 = (@137-@89) */
  w137 -= w89;
  /* #782: @100 = (@100+@137) */
  w100 += w137;
  /* #783: @100 = (@16*@100) */
  w100  = (w16*w100);
  /* #784: @99 = (@10*@99) */
  w99  = (w10*w99);
  /* #785: @137 = (@1*@101) */
  w137  = (w1*w101);
  /* #786: @99 = (@99+@137) */
  w99 += w137;
  /* #787: @100 = (@100-@99) */
  w100 -= w99;
  /* #788: @120 = (@42*@120) */
  w120  = (w42*w120);
  /* #789: @120 = (@44*@120) */
  w120  = (w44*w120);
  /* #790: @102 = (@144*@102) */
  w102  = (w144*w102);
  /* #791: @102 = (@43*@102) */
  w102  = (w43*w102);
  /* #792: @120 = (@120-@102) */
  w120 -= w102;
  /* #793: @103 = (@46*@103) */
  w103  = (w46*w103);
  /* #794: @103 = (@48*@103) */
  w103  = (w48*w103);
  /* #795: @102 = (@45*@98) */
  w102  = (w45*w98);
  /* #796: @102 = (@47*@102) */
  w102  = (w47*w102);
  /* #797: @103 = (@103+@102) */
  w103 += w102;
  /* #798: @120 = (@120-@103) */
  w120 -= w103;
  /* #799: @94 = (@49*@94) */
  w94  = (w49*w94);
  /* #800: @94 = (@51*@94) */
  w94  = (w51*w94);
  /* #801: @98 = (@52*@98) */
  w98  = (w52*w98);
  /* #802: @98 = (@50*@98) */
  w98  = (w50*w98);
  /* #803: @94 = (@94-@98) */
  w94 -= w98;
  /* #804: @120 = (@120-@94) */
  w120 -= w94;
  /* #805: @120 = (@8*@120) */
  w120  = (w8*w120);
  /* #806: @72 = 00 */
  /* #807: @148 = 00 */
  /* #808: @149 = vertcat(@53, @64, @101, @95, @100, @120, @72, @148) */
  rr=w149;
  *rr++ = w53;
  *rr++ = w64;
  *rr++ = w101;
  *rr++ = w95;
  *rr++ = w100;
  *rr++ = w120;
  /* #809: @149 = (@0*@149) */
  for (i=0, rr=w149, cs=w149; i<6; ++i) (*rr++)  = (w0*(*cs++));
  /* #810: output[1][5] = @149 */
  if (res[1]) casadi_copy(w149, 6, res[1]+30);
  /* #811: @53 = (@3*@105) */
  w53  = (w3*w105);
  /* #812: @64 = (@63*@104) */
  w64  = (w63*w104);
  /* #813: @64 = (@1*@64) */
  w64  = (w1*w64);
  /* #814: @53 = (@53-@64) */
  w53 -= w64;
  /* #815: @64 = (@6*@106) */
  w64  = (w6*w106);
  /* #816: @101 = (@65*@104) */
  w101  = (w65*w104);
  /* #817: @101 = (@5*@101) */
  w101  = (w5*w101);
  /* #818: @64 = (@64+@101) */
  w64 += w101;
  /* #819: @53 = (@53-@64) */
  w53 -= w64;
  /* #820: @64 = (@7*@105) */
  w64  = (w7*w105);
  /* #821: @101 = (@66*@104) */
  w101  = (w66*w104);
  /* #822: @101 = (@1*@101) */
  w101  = (w1*w101);
  /* #823: @64 = (@64+@101) */
  w64 += w101;
  /* #824: @101 = (@9*@106) */
  w101  = (w9*w106);
  /* #825: @104 = (@68*@104) */
  w104  = (w68*w104);
  /* #826: @104 = (@5*@104) */
  w104  = (w5*w104);
  /* #827: @101 = (@101-@104) */
  w101 -= w104;
  /* #828: @64 = (@64+@101) */
  w64 += w101;
  /* #829: @109 = (@4*@109) */
  w109  = (w4*w109);
  /* #830: @101 = (@15*@109) */
  w101  = (w15*w109);
  /* #831: @104 = (@13*@108) */
  w104  = (w13*w108);
  /* #832: @121 = (@12*@121) */
  w121  = (w12*w121);
  /* #833: @104 = (@104+@121) */
  w104 += w121;
  /* #834: @121 = (@70*@104) */
  w121  = (w70*w104);
  /* #835: @121 = (@11*@121) */
  w121  = (w11*w121);
  /* #836: @101 = (@101-@121) */
  w101 -= w121;
  /* #837: @121 = (@20*@107) */
  w121  = (w20*w107);
  /* #838: @121 = (@106+@121) */
  w121  = (w106+w121);
  /* #839: @121 = (@124*@121) */
  w121  = (w124*w121);
  /* #840: @95 = (@126*@105) */
  w95  = (w126*w105);
  /* #841: @100 = (@123*@95) */
  w100  = (w123*w95);
  /* #842: @121 = (@121-@100) */
  w121 -= w100;
  /* #843: @121 = (@108-@121) */
  w121  = (w108-w121);
  /* #844: @121 = (@19*@121) */
  w121  = (w19*w121);
  /* #845: @121 = (@121/@128) */
  w121 /= w128;
  /* #846: @121 = (@18*@121) */
  w121  = (w18*w121);
  /* #847: @121 = (@73*@121) */
  w121  = (w73*w121);
  /* #848: @121 = (@17*@121) */
  w121  = (w17*w121);
  /* #849: @100 = (@27*@121) */
  w100  = (w27*w121);
  /* #850: @120 = (@130*@108) */
  w120  = (w130*w108);
  /* #851: @120 = (@26*@120) */
  w120  = (w26*w120);
  /* #852: @100 = (@100+@120) */
  w100 += w120;
  /* #853: @101 = (@101-@100) */
  w101 -= w100;
  /* #854: @100 = (@31*@108) */
  w100  = (w31*w108);
  /* #855: @138 = (@12*@138) */
  w138  = (w12*w138);
  /* #856: @100 = (@100+@138) */
  w100 += w138;
  /* #857: @138 = (@33*@107) */
  w138  = (w33*w107);
  /* #858: @138 = (@106-@138) */
  w138  = (w106-w138);
  /* #859: @138 = (@140*@138) */
  w138  = (w140*w138);
  /* #860: @95 = (@132*@95) */
  w95  = (w132*w95);
  /* #861: @138 = (@138-@95) */
  w138 -= w95;
  /* #862: @100 = (@100-@138) */
  w100 -= w138;
  /* #863: @100 = (@30*@100) */
  w100  = (w30*w100);
  /* #864: @100 = (@100/@141) */
  w100 /= w141;
  /* #865: @100 = (@29*@100) */
  w100  = (w29*w100);
  /* #866: @100 = (@129*@100) */
  w100  = (w129*w100);
  /* #867: @100 = (@28*@100) */
  w100  = (w28*w100);
  /* #868: @138 = (@37*@100) */
  w138  = (w37*w100);
  /* #869: @95 = (@142*@104) */
  w95  = (w142*w104);
  /* #870: @95 = (@36*@95) */
  w95  = (w36*w95);
  /* #871: @138 = (@138+@95) */
  w138 += w95;
  /* #872: @101 = (@101-@138) */
  w101 -= w138;
  /* #873: @101 = (@67*@101) */
  w101  = (w67*w101);
  /* #874: @106 = (@10*@106) */
  w106  = (w10*w106);
  /* #875: @138 = (@5*@107) */
  w138  = (w5*w107);
  /* #876: @106 = (@106+@138) */
  w106 += w138;
  /* #877: @101 = (@101+@106) */
  w101 += w106;
  /* #878: @106 = (@38*@121) */
  w106  = (w38*w121);
  /* #879: @138 = (@143*@108) */
  w138  = (w143*w108);
  /* #880: @138 = (@26*@138) */
  w138  = (w26*w138);
  /* #881: @106 = (@106-@138) */
  w106 -= w138;
  /* #882: @138 = (@40*@109) */
  w138  = (w40*w109);
  /* #883: @95 = (@145*@104) */
  w95  = (w145*w104);
  /* #884: @95 = (@11*@95) */
  w95  = (w11*w95);
  /* #885: @138 = (@138+@95) */
  w138 += w95;
  /* #886: @106 = (@106+@138) */
  w106 += w138;
  /* #887: @138 = (@41*@100) */
  w138  = (w41*w100);
  /* #888: @95 = (@146*@104) */
  w95  = (w146*w104);
  /* #889: @95 = (@36*@95) */
  w95  = (w36*w95);
  /* #890: @138 = (@138-@95) */
  w138 -= w95;
  /* #891: @106 = (@106+@138) */
  w106 += w138;
  /* #892: @106 = (@16*@106) */
  w106  = (w16*w106);
  /* #893: @105 = (@10*@105) */
  w105  = (w10*w105);
  /* #894: @138 = (@1*@107) */
  w138  = (w1*w107);
  /* #895: @105 = (@105+@138) */
  w105 += w138;
  /* #896: @106 = (@106-@105) */
  w106 -= w105;
  /* #897: @121 = (@42*@121) */
  w121  = (w42*w121);
  /* #898: @121 = (@44*@121) */
  w121  = (w44*w121);
  /* #899: @108 = (@144*@108) */
  w108  = (w144*w108);
  /* #900: @108 = (@43*@108) */
  w108  = (w43*w108);
  /* #901: @121 = (@121-@108) */
  w121 -= w108;
  /* #902: @109 = (@46*@109) */
  w109  = (w46*w109);
  /* #903: @109 = (@48*@109) */
  w109  = (w48*w109);
  /* #904: @108 = (@45*@104) */
  w108  = (w45*w104);
  /* #905: @108 = (@47*@108) */
  w108  = (w47*w108);
  /* #906: @109 = (@109+@108) */
  w109 += w108;
  /* #907: @121 = (@121-@109) */
  w121 -= w109;
  /* #908: @100 = (@49*@100) */
  w100  = (w49*w100);
  /* #909: @100 = (@51*@100) */
  w100  = (w51*w100);
  /* #910: @104 = (@52*@104) */
  w104  = (w52*w104);
  /* #911: @104 = (@50*@104) */
  w104  = (w50*w104);
  /* #912: @100 = (@100-@104) */
  w100 -= w104;
  /* #913: @121 = (@121-@100) */
  w121 -= w100;
  /* #914: @121 = (@8*@121) */
  w121  = (w8*w121);
  /* #915: @72 = 00 */
  /* #916: @148 = 00 */
  /* #917: @149 = vertcat(@53, @64, @107, @101, @106, @121, @72, @148) */
  rr=w149;
  *rr++ = w53;
  *rr++ = w64;
  *rr++ = w107;
  *rr++ = w101;
  *rr++ = w106;
  *rr++ = w121;
  /* #918: @149 = (@0*@149) */
  for (i=0, rr=w149, cs=w149; i<6; ++i) (*rr++)  = (w0*(*cs++));
  /* #919: output[1][6] = @149 */
  if (res[1]) casadi_copy(w149, 6, res[1]+36);
  /* #920: @53 = (@3*@111) */
  w53  = (w3*w111);
  /* #921: @63 = (@63*@110) */
  w63 *= w110;
  /* #922: @63 = (@1*@63) */
  w63  = (w1*w63);
  /* #923: @53 = (@53-@63) */
  w53 -= w63;
  /* #924: @63 = (@6*@112) */
  w63  = (w6*w112);
  /* #925: @65 = (@65*@110) */
  w65 *= w110;
  /* #926: @65 = (@5*@65) */
  w65  = (w5*w65);
  /* #927: @63 = (@63+@65) */
  w63 += w65;
  /* #928: @53 = (@53-@63) */
  w53 -= w63;
  /* #929: @63 = (@7*@111) */
  w63  = (w7*w111);
  /* #930: @66 = (@66*@110) */
  w66 *= w110;
  /* #931: @66 = (@1*@66) */
  w66  = (w1*w66);
  /* #932: @63 = (@63+@66) */
  w63 += w66;
  /* #933: @66 = (@9*@112) */
  w66  = (w9*w112);
  /* #934: @68 = (@68*@110) */
  w68 *= w110;
  /* #935: @68 = (@5*@68) */
  w68  = (w5*w68);
  /* #936: @66 = (@66-@68) */
  w66 -= w68;
  /* #937: @63 = (@63+@66) */
  w63 += w66;
  /* #938: @4 = (@4*@115) */
  w4 *= w115;
  /* #939: @115 = (@15*@4) */
  w115  = (w15*w4);
  /* #940: @66 = (@13*@114) */
  w66  = (w13*w114);
  /* #941: @122 = (@12*@122) */
  w122  = (w12*w122);
  /* #942: @66 = (@66+@122) */
  w66 += w122;
  /* #943: @70 = (@70*@66) */
  w70 *= w66;
  /* #944: @70 = (@11*@70) */
  w70  = (w11*w70);
  /* #945: @115 = (@115-@70) */
  w115 -= w70;
  /* #946: @70 = (@20*@113) */
  w70  = (w20*w113);
  /* #947: @70 = (@112+@70) */
  w70  = (w112+w70);
  /* #948: @124 = (@124*@70) */
  w124 *= w70;
  /* #949: @126 = (@126*@111) */
  w126 *= w111;
  /* #950: @123 = (@123*@126) */
  w123 *= w126;
  /* #951: @124 = (@124-@123) */
  w124 -= w123;
  /* #952: @124 = (@114-@124) */
  w124  = (w114-w124);
  /* #953: @124 = (@19*@124) */
  w124  = (w19*w124);
  /* #954: @124 = (@124/@128) */
  w124 /= w128;
  /* #955: @124 = (@18*@124) */
  w124  = (w18*w124);
  /* #956: @73 = (@73*@124) */
  w73 *= w124;
  /* #957: @73 = (@17*@73) */
  w73  = (w17*w73);
  /* #958: @124 = (@27*@73) */
  w124  = (w27*w73);
  /* #959: @130 = (@130*@114) */
  w130 *= w114;
  /* #960: @130 = (@26*@130) */
  w130  = (w26*w130);
  /* #961: @124 = (@124+@130) */
  w124 += w130;
  /* #962: @115 = (@115-@124) */
  w115 -= w124;
  /* #963: @124 = (@31*@114) */
  w124  = (w31*w114);
  /* #964: @139 = (@12*@139) */
  w139  = (w12*w139);
  /* #965: @124 = (@124+@139) */
  w124 += w139;
  /* #966: @139 = (@33*@113) */
  w139  = (w33*w113);
  /* #967: @139 = (@112-@139) */
  w139  = (w112-w139);
  /* #968: @140 = (@140*@139) */
  w140 *= w139;
  /* #969: @132 = (@132*@126) */
  w132 *= w126;
  /* #970: @140 = (@140-@132) */
  w140 -= w132;
  /* #971: @124 = (@124-@140) */
  w124 -= w140;
  /* #972: @124 = (@30*@124) */
  w124  = (w30*w124);
  /* #973: @124 = (@124/@141) */
  w124 /= w141;
  /* #974: @124 = (@29*@124) */
  w124  = (w29*w124);
  /* #975: @129 = (@129*@124) */
  w129 *= w124;
  /* #976: @129 = (@28*@129) */
  w129  = (w28*w129);
  /* #977: @124 = (@37*@129) */
  w124  = (w37*w129);
  /* #978: @142 = (@142*@66) */
  w142 *= w66;
  /* #979: @142 = (@36*@142) */
  w142  = (w36*w142);
  /* #980: @124 = (@124+@142) */
  w124 += w142;
  /* #981: @115 = (@115-@124) */
  w115 -= w124;
  /* #982: @67 = (@67*@115) */
  w67 *= w115;
  /* #983: @112 = (@10*@112) */
  w112  = (w10*w112);
  /* #984: @115 = (@5*@113) */
  w115  = (w5*w113);
  /* #985: @112 = (@112+@115) */
  w112 += w115;
  /* #986: @67 = (@67+@112) */
  w67 += w112;
  /* #987: @112 = (@38*@73) */
  w112  = (w38*w73);
  /* #988: @143 = (@143*@114) */
  w143 *= w114;
  /* #989: @143 = (@26*@143) */
  w143  = (w26*w143);
  /* #990: @112 = (@112-@143) */
  w112 -= w143;
  /* #991: @143 = (@40*@4) */
  w143  = (w40*w4);
  /* #992: @145 = (@145*@66) */
  w145 *= w66;
  /* #993: @145 = (@11*@145) */
  w145  = (w11*w145);
  /* #994: @143 = (@143+@145) */
  w143 += w145;
  /* #995: @112 = (@112+@143) */
  w112 += w143;
  /* #996: @143 = (@41*@129) */
  w143  = (w41*w129);
  /* #997: @146 = (@146*@66) */
  w146 *= w66;
  /* #998: @146 = (@36*@146) */
  w146  = (w36*w146);
  /* #999: @143 = (@143-@146) */
  w143 -= w146;
  /* #1000: @112 = (@112+@143) */
  w112 += w143;
  /* #1001: @16 = (@16*@112) */
  w16 *= w112;
  /* #1002: @111 = (@10*@111) */
  w111  = (w10*w111);
  /* #1003: @112 = (@1*@113) */
  w112  = (w1*w113);
  /* #1004: @111 = (@111+@112) */
  w111 += w112;
  /* #1005: @16 = (@16-@111) */
  w16 -= w111;
  /* #1006: @73 = (@42*@73) */
  w73  = (w42*w73);
  /* #1007: @73 = (@44*@73) */
  w73  = (w44*w73);
  /* #1008: @144 = (@144*@114) */
  w144 *= w114;
  /* #1009: @144 = (@43*@144) */
  w144  = (w43*w144);
  /* #1010: @73 = (@73-@144) */
  w73 -= w144;
  /* #1011: @4 = (@46*@4) */
  w4  = (w46*w4);
  /* #1012: @4 = (@48*@4) */
  w4  = (w48*w4);
  /* #1013: @45 = (@45*@66) */
  w45 *= w66;
  /* #1014: @45 = (@47*@45) */
  w45  = (w47*w45);
  /* #1015: @4 = (@4+@45) */
  w4 += w45;
  /* #1016: @73 = (@73-@4) */
  w73 -= w4;
  /* #1017: @129 = (@49*@129) */
  w129  = (w49*w129);
  /* #1018: @129 = (@51*@129) */
  w129  = (w51*w129);
  /* #1019: @52 = (@52*@66) */
  w52 *= w66;
  /* #1020: @52 = (@50*@52) */
  w52  = (w50*w52);
  /* #1021: @129 = (@129-@52) */
  w129 -= w52;
  /* #1022: @73 = (@73-@129) */
  w73 -= w129;
  /* #1023: @8 = (@8*@73) */
  w8 *= w73;
  /* #1024: @72 = 00 */
  /* #1025: @148 = 00 */
  /* #1026: @149 = vertcat(@53, @63, @113, @67, @16, @8, @72, @148) */
  rr=w149;
  *rr++ = w53;
  *rr++ = w63;
  *rr++ = w113;
  *rr++ = w67;
  *rr++ = w16;
  *rr++ = w8;
  /* #1027: @149 = (@0*@149) */
  for (i=0, rr=w149, cs=w149; i<6; ++i) (*rr++)  = (w0*(*cs++));
  /* #1028: output[1][7] = @149 */
  if (res[1]) casadi_copy(w149, 6, res[1]+42);
  /* #1029: @53 = zeros(1x8,1nz) */
  w53 = 0.;
  /* #1030: @72 = 00 */
  /* #1031: @148 = 00 */
  /* #1032: @150 = 00 */
  /* #1033: @151 = 00 */
  /* #1034: @152 = 00 */
  /* #1035: @153 = 00 */
  /* #1036: @63 = 1 */
  w63 = 1.;
  /* #1037: @154 = 00 */
  /* #1038: @113 = vertcat(@72, @148, @150, @151, @152, @153, @63, @154) */
  rr=(&w113);
  *rr++ = w63;
  /* #1039: @113 = (@0*@113) */
  w113  = (w0*w113);
  /* #1040: @63 = @113[0] */
  for (rr=(&w63), ss=(&w113)+0; ss!=(&w113)+1; ss+=1) *rr++ = *ss;
  /* #1041: (@53[0] = @63) */
  for (rr=(&w53)+0, ss=(&w63); rr!=(&w53)+1; rr+=1) *rr = *ss++;
  /* #1042: @53 = @53' */
  /* #1043: @155 = project(@53) */
  casadi_project((&w53), casadi_s6, w155, casadi_s7, w);
  /* #1044: @62 = input[2][0] */
  casadi_copy(arg[2], 8, w62);
  /* #1045: {NULL, NULL, @53, @63, @113, @67, @16, @8} = vertsplit(@62) */
  w53 = w62[2];
  w63 = w62[3];
  w113 = w62[4];
  w67 = w62[5];
  w16 = w62[6];
  w8 = w62[7];
  /* #1046: @3 = (@3*@63) */
  w3 *= w63;
  /* #1047: @73 = sin(@2) */
  w73 = sin( w2 );
  /* #1048: @73 = (@73*@53) */
  w73 *= w53;
  /* #1049: @73 = (@1*@73) */
  w73  = (w1*w73);
  /* #1050: @3 = (@3-@73) */
  w3 -= w73;
  /* #1051: @6 = (@6*@113) */
  w6 *= w113;
  /* #1052: @73 = cos(@2) */
  w73 = cos( w2 );
  /* #1053: @73 = (@73*@53) */
  w73 *= w53;
  /* #1054: @73 = (@5*@73) */
  w73  = (w5*w73);
  /* #1055: @6 = (@6+@73) */
  w6 += w73;
  /* #1056: @3 = (@3-@6) */
  w3 -= w6;
  /* #1057: @7 = (@7*@63) */
  w7 *= w63;
  /* #1058: @6 = cos(@2) */
  w6 = cos( w2 );
  /* #1059: @6 = (@6*@53) */
  w6 *= w53;
  /* #1060: @6 = (@1*@6) */
  w6  = (w1*w6);
  /* #1061: @7 = (@7+@6) */
  w7 += w6;
  /* #1062: @9 = (@9*@113) */
  w9 *= w113;
  /* #1063: @2 = sin(@2) */
  w2 = sin( w2 );
  /* #1064: @2 = (@2*@53) */
  w2 *= w53;
  /* #1065: @2 = (@5*@2) */
  w2  = (w5*w2);
  /* #1066: @9 = (@9-@2) */
  w9 -= w2;
  /* #1067: @7 = (@7+@9) */
  w7 += w9;
  /* #1068: @9 = 0.000437951 */
  w9 = 4.3795108962231094e-04;
  /* #1069: @2 = 2.71186 */
  w2 = 2.7118644067796609e+00;
  /* #1070: @2 = (@2*@8) */
  w2 *= w8;
  /* #1071: @15 = (@15*@2) */
  w15 *= w2;
  /* #1072: @8 = sin(@14) */
  w8 = sin( w14 );
  /* #1073: @13 = (@13*@16) */
  w13 *= w16;
  /* #1074: @72 = 00 */
  /* #1075: @53 = fwd1_mapping(@1, @72, @63) */
  arg1[0]=(&w1);
  arg1[1]=0;
  arg1[2]=(&w63);
  res1[0]=(&w53);
  if (casadi_f5(arg1, res1, iw, w, 0)) return 1;
  /* #1076: @53 = (@12*@53) */
  w53  = (w12*w53);
  /* #1077: @13 = (@13+@53) */
  w13 += w53;
  /* #1078: @8 = (@8*@13) */
  w8 *= w13;
  /* #1079: @8 = (@11*@8) */
  w8  = (w11*w8);
  /* #1080: @15 = (@15-@8) */
  w15 -= w8;
  /* #1081: @25 = cos(@25) */
  w25 = cos( w25 );
  /* #1082: @8 = sq(@21) */
  w8 = casadi_sq( w21 );
  /* #1083: @53 = sq(@23) */
  w53 = casadi_sq( w23 );
  /* #1084: @8 = (@8+@53) */
  w8 += w53;
  /* #1085: @53 = (@23/@8) */
  w53  = (w23/w8);
  /* #1086: @20 = (@20*@67) */
  w20 *= w67;
  /* #1087: @20 = (@113+@20) */
  w20  = (w113+w20);
  /* #1088: @53 = (@53*@20) */
  w53 *= w20;
  /* #1089: @21 = (@21/@8) */
  w21 /= w8;
  /* #1090: @8 = (@22<=@1) */
  w8  = (w22<=w1);
  /* #1091: @22 = (@1<=@22) */
  w22  = (w1<=w22);
  /* #1092: @22 = (@8+@22) */
  w22  = (w8+w22);
  /* #1093: @8 = (@8/@22) */
  w8 /= w22;
  /* #1094: @8 = (@8*@63) */
  w8 *= w63;
  /* #1095: @21 = (@21*@8) */
  w21 *= w8;
  /* #1096: @53 = (@53-@21) */
  w53 -= w21;
  /* #1097: @53 = (@16-@53) */
  w53  = (w16-w53);
  /* #1098: @19 = (@19*@53) */
  w19 *= w53;
  /* #1099: @53 = 1 */
  w53 = 1.;
  /* #1100: @24 = sq(@24) */
  w24 = casadi_sq( w24 );
  /* #1101: @53 = (@53+@24) */
  w53 += w24;
  /* #1102: @19 = (@19/@53) */
  w19 /= w53;
  /* #1103: @18 = (@18*@19) */
  w18 *= w19;
  /* #1104: @25 = (@25*@18) */
  w25 *= w18;
  /* #1105: @17 = (@17*@25) */
  w17 *= w25;
  /* #1106: @27 = (@27*@17) */
  w27 *= w17;
  /* #1107: @25 = cos(@12) */
  w25 = cos( w12 );
  /* #1108: @25 = (@25*@16) */
  w25 *= w16;
  /* #1109: @25 = (@26*@25) */
  w25  = (w26*w25);
  /* #1110: @27 = (@27+@25) */
  w27 += w25;
  /* #1111: @15 = (@15-@27) */
  w15 -= w27;
  /* #1112: @35 = cos(@35) */
  w35 = cos( w35 );
  /* #1113: @31 = (@31*@16) */
  w31 *= w16;
  /* #1114: @72 = 00 */
  /* #1115: @27 = fwd1_mapping(@1, @72, @63) */
  arg1[0]=(&w1);
  arg1[1]=0;
  arg1[2]=(&w63);
  res1[0]=(&w27);
  if (casadi_f6(arg1, res1, iw, w, 0)) return 1;
  /* #1116: @27 = (@12*@27) */
  w27  = (w12*w27);
  /* #1117: @31 = (@31+@27) */
  w31 += w27;
  /* #1118: @27 = sq(@34) */
  w27 = casadi_sq( w34 );
  /* #1119: @25 = sq(@23) */
  w25 = casadi_sq( w23 );
  /* #1120: @27 = (@27+@25) */
  w27 += w25;
  /* #1121: @23 = (@23/@27) */
  w23 /= w27;
  /* #1122: @33 = (@33*@67) */
  w33 *= w67;
  /* #1123: @33 = (@113-@33) */
  w33  = (w113-w33);
  /* #1124: @23 = (@23*@33) */
  w23 *= w33;
  /* #1125: @34 = (@34/@27) */
  w34 /= w27;
  /* #1126: @34 = (@34*@8) */
  w34 *= w8;
  /* #1127: @23 = (@23-@34) */
  w23 -= w34;
  /* #1128: @31 = (@31-@23) */
  w31 -= w23;
  /* #1129: @30 = (@30*@31) */
  w30 *= w31;
  /* #1130: @31 = 1 */
  w31 = 1.;
  /* #1131: @32 = sq(@32) */
  w32 = casadi_sq( w32 );
  /* #1132: @31 = (@31+@32) */
  w31 += w32;
  /* #1133: @30 = (@30/@31) */
  w30 /= w31;
  /* #1134: @29 = (@29*@30) */
  w29 *= w30;
  /* #1135: @35 = (@35*@29) */
  w35 *= w29;
  /* #1136: @28 = (@28*@35) */
  w28 *= w35;
  /* #1137: @37 = (@37*@28) */
  w37 *= w28;
  /* #1138: @35 = cos(@14) */
  w35 = cos( w14 );
  /* #1139: @35 = (@35*@13) */
  w35 *= w13;
  /* #1140: @35 = (@36*@35) */
  w35  = (w36*w35);
  /* #1141: @37 = (@37+@35) */
  w37 += w35;
  /* #1142: @15 = (@15-@37) */
  w15 -= w37;
  /* #1143: @9 = (@9*@15) */
  w9 *= w15;
  /* #1144: @113 = (@10*@113) */
  w113  = (w10*w113);
  /* #1145: @5 = (@5*@67) */
  w5 *= w67;
  /* #1146: @113 = (@113+@5) */
  w113 += w5;
  /* #1147: @9 = (@9+@113) */
  w9 += w113;
  /* #1148: @113 = 0.000437951 */
  w113 = 4.3795108962231094e-04;
  /* #1149: @38 = (@38*@17) */
  w38 *= w17;
  /* #1150: @5 = sin(@12) */
  w5 = sin( w12 );
  /* #1151: @5 = (@5*@16) */
  w5 *= w16;
  /* #1152: @26 = (@26*@5) */
  w26 *= w5;
  /* #1153: @38 = (@38-@26) */
  w38 -= w26;
  /* #1154: @40 = (@40*@2) */
  w40 *= w2;
  /* #1155: @26 = cos(@14) */
  w26 = cos( w14 );
  /* #1156: @26 = (@26*@13) */
  w26 *= w13;
  /* #1157: @11 = (@11*@26) */
  w11 *= w26;
  /* #1158: @40 = (@40+@11) */
  w40 += w11;
  /* #1159: @38 = (@38+@40) */
  w38 += w40;
  /* #1160: @41 = (@41*@28) */
  w41 *= w28;
  /* #1161: @40 = sin(@14) */
  w40 = sin( w14 );
  /* #1162: @40 = (@40*@13) */
  w40 *= w13;
  /* #1163: @36 = (@36*@40) */
  w36 *= w40;
  /* #1164: @41 = (@41-@36) */
  w41 -= w36;
  /* #1165: @38 = (@38+@41) */
  w38 += w41;
  /* #1166: @113 = (@113*@38) */
  w113 *= w38;
  /* #1167: @10 = (@10*@63) */
  w10 *= w63;
  /* #1168: @1 = (@1*@67) */
  w1 *= w67;
  /* #1169: @10 = (@10+@1) */
  w10 += w1;
  /* #1170: @113 = (@113-@10) */
  w113 -= w10;
  /* #1171: @10 = 0.000215054 */
  w10 = 2.1505376344086021e-04;
  /* #1172: @42 = (@42*@17) */
  w42 *= w17;
  /* #1173: @44 = (@44*@42) */
  w44 *= w42;
  /* #1174: @12 = sin(@12) */
  w12 = sin( w12 );
  /* #1175: @12 = (@12*@16) */
  w12 *= w16;
  /* #1176: @43 = (@43*@12) */
  w43 *= w12;
  /* #1177: @44 = (@44-@43) */
  w44 -= w43;
  /* #1178: @46 = (@46*@2) */
  w46 *= w2;
  /* #1179: @48 = (@48*@46) */
  w48 *= w46;
  /* #1180: @46 = cos(@14) */
  w46 = cos( w14 );
  /* #1181: @46 = (@46*@13) */
  w46 *= w13;
  /* #1182: @47 = (@47*@46) */
  w47 *= w46;
  /* #1183: @48 = (@48+@47) */
  w48 += w47;
  /* #1184: @44 = (@44-@48) */
  w44 -= w48;
  /* #1185: @49 = (@49*@28) */
  w49 *= w28;
  /* #1186: @51 = (@51*@49) */
  w51 *= w49;
  /* #1187: @14 = sin(@14) */
  w14 = sin( w14 );
  /* #1188: @14 = (@14*@13) */
  w14 *= w13;
  /* #1189: @50 = (@50*@14) */
  w50 *= w14;
  /* #1190: @51 = (@51-@50) */
  w51 -= w50;
  /* #1191: @44 = (@44-@51) */
  w44 -= w51;
  /* #1192: @10 = (@10*@44) */
  w10 *= w44;
  /* #1193: @72 = 00 */
  /* #1194: @148 = 00 */
  /* #1195: @149 = vertcat(@3, @7, @67, @9, @113, @10, @72, @148) */
  rr=w149;
  *rr++ = w3;
  *rr++ = w7;
  *rr++ = w67;
  *rr++ = w9;
  *rr++ = w113;
  *rr++ = w10;
  /* #1196: @149 = (@0*@149) */
  for (i=0, rr=w149, cs=w149; i<6; ++i) (*rr++)  = (w0*(*cs++));
  /* #1197: @156 = project(@149) */
  casadi_project(w149, casadi_s8, w156, casadi_s7, w);
  /* #1198: @155 = (@155+@156) */
  for (i=0, rr=w155, cs=w156; i<7; ++i) (*rr++) += (*cs++);
  /* #1199: output[2][0] = @155 */
  casadi_copy(w155, 7, res[2]);
  return 0;
}

CASADI_SYMBOL_EXPORT int Path_parametric_MPC_expl_vde_forw(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int Path_parametric_MPC_expl_vde_forw_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int Path_parametric_MPC_expl_vde_forw_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void Path_parametric_MPC_expl_vde_forw_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int Path_parametric_MPC_expl_vde_forw_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void Path_parametric_MPC_expl_vde_forw_release(int mem) {
}

CASADI_SYMBOL_EXPORT void Path_parametric_MPC_expl_vde_forw_incref(void) {
}

CASADI_SYMBOL_EXPORT void Path_parametric_MPC_expl_vde_forw_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int Path_parametric_MPC_expl_vde_forw_n_in(void) { return 5;}

CASADI_SYMBOL_EXPORT casadi_int Path_parametric_MPC_expl_vde_forw_n_out(void) { return 3;}

CASADI_SYMBOL_EXPORT casadi_real Path_parametric_MPC_expl_vde_forw_default_in(casadi_int i) {
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* Path_parametric_MPC_expl_vde_forw_name_in(casadi_int i) {
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    case 3: return "i3";
    case 4: return "i4";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* Path_parametric_MPC_expl_vde_forw_name_out(casadi_int i) {
  switch (i) {
    case 0: return "o0";
    case 1: return "o1";
    case 2: return "o2";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* Path_parametric_MPC_expl_vde_forw_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s9;
    case 1: return casadi_s10;
    case 2: return casadi_s9;
    case 3: return casadi_s11;
    case 4: return casadi_s12;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* Path_parametric_MPC_expl_vde_forw_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s9;
    case 1: return casadi_s13;
    case 2: return casadi_s7;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int Path_parametric_MPC_expl_vde_forw_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 13;
  if (sz_res) *sz_res = 11;
  if (sz_iw) *sz_iw = 8;
  if (sz_w) *sz_w = 298;
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
