/* This file was automatically generated by CasADi 3.6.3.
 *  It consists of: 
 *   1) content generated by CasADi runtime: not copyrighted
 *   2) template code copied from CasADi source: permissively licensed (MIT-0)
 *   3) user code: owned by the user
 *
 */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) Path_parametric_MPC_expl_ode_fun_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int int
#endif

/* Add prefix to internal symbols */
#define casadi_c0 CASADI_PREFIX(c0)
#define casadi_c1 CASADI_PREFIX(c1)
#define casadi_clear CASADI_PREFIX(clear)
#define casadi_clear_casadi_int CASADI_PREFIX(clear_casadi_int)
#define casadi_copy CASADI_PREFIX(copy)
#define casadi_de_boor CASADI_PREFIX(de_boor)
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_f1 CASADI_PREFIX(f1)
#define casadi_f2 CASADI_PREFIX(f2)
#define casadi_fill CASADI_PREFIX(fill)
#define casadi_fill_casadi_int CASADI_PREFIX(fill_casadi_int)
#define casadi_fmax CASADI_PREFIX(fmax)
#define casadi_low CASADI_PREFIX(low)
#define casadi_nd_boor_eval CASADI_PREFIX(nd_boor_eval)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_s2 CASADI_PREFIX(s2)
#define casadi_s3 CASADI_PREFIX(s3)
#define casadi_s4 CASADI_PREFIX(s4)
#define casadi_s5 CASADI_PREFIX(s5)
#define casadi_s6 CASADI_PREFIX(s6)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

void casadi_de_boor(casadi_real x, const casadi_real* knots, casadi_int n_knots, casadi_int degree, casadi_real* boor) {
  casadi_int d, i;
  for (d=1;d<degree+1;++d) {
    for (i=0;i<n_knots-d-1;++i) {
      casadi_real b, bottom;
      b = 0;
      bottom = knots[i + d] - knots[i];
      if (bottom) b = (x - knots[i]) * boor[i] / bottom;
      bottom = knots[i + d + 1] - knots[i + 1];
      if (bottom) b += (knots[i + d + 1] - x) * boor[i + 1] / bottom;
      boor[i] = b;
    }
  }
}

void casadi_fill(casadi_real* x, casadi_int n, casadi_real alpha) {
  casadi_int i;
  if (x) {
    for (i=0; i<n; ++i) *x++ = alpha;
  }
}

void casadi_fill_casadi_int(casadi_int* x, casadi_int n, casadi_int alpha) {
  casadi_int i;
  if (x) {
    for (i=0; i<n; ++i) *x++ = alpha;
  }
}

void casadi_clear(casadi_real* x, casadi_int n) {
  casadi_int i;
  if (x) {
    for (i=0; i<n; ++i) *x++ = 0;
  }
}

void casadi_clear_casadi_int(casadi_int* x, casadi_int n) {
  casadi_int i;
  if (x) {
    for (i=0; i<n; ++i) *x++ = 0;
  }
}

casadi_int casadi_low(casadi_real x, const casadi_real* grid, casadi_int ng, casadi_int lookup_mode) {
  switch (lookup_mode) {
    case 1:
      {
        casadi_real g0, dg;
        casadi_int ret;
        g0 = grid[0];
        dg = grid[ng-1]-g0;
        ret = (casadi_int) ((x-g0)*(ng-1)/dg);
        if (ret<0) ret=0;
        if (ret>ng-2) ret=ng-2;
        return ret;
      }
    case 2:
      {
        casadi_int start, stop, pivot;
        if (ng<2 || x<grid[1]) return 0;
        if (x>grid[ng-1]) return ng-2;
        start = 0;
        stop  = ng-1;
        while (1) {
          pivot = (stop+start)/2;
          if (x < grid[pivot]) {
            if (pivot==stop) return pivot;
            stop = pivot;
          } else {
            if (pivot==start) return pivot;
            start = pivot;
          }
        }
      }
    default:
      {
        casadi_int i;
        for (i=0; i<ng-2; ++i) {
          if (x < grid[i+1]) break;
        }
        return i;
      }
  }
}

void casadi_nd_boor_eval(casadi_real* ret, casadi_int n_dims, const casadi_real* all_knots, const casadi_int* offset, const casadi_int* all_degree, const casadi_int* strides, const casadi_real* c, casadi_int m, const casadi_real* all_x, const casadi_int* lookup_mode, casadi_int* iw, casadi_real* w) {
  casadi_int n_iter, k, i, pivot;
  casadi_int *boor_offset, *starts, *index, *coeff_offset;
  casadi_real *cumprod, *all_boor;
  boor_offset = iw; iw+=n_dims+1;
  starts = iw; iw+=n_dims;
  index = iw; iw+=n_dims;
  coeff_offset = iw;
  cumprod = w; w+= n_dims+1;
  all_boor = w;
  boor_offset[0] = 0;
  cumprod[n_dims] = 1;
  coeff_offset[n_dims] = 0;
  n_iter = 1;
  for (k=0;k<n_dims;++k) {
    casadi_real *boor;
    const casadi_real* knots;
    casadi_real x;
    casadi_int degree, n_knots, n_b, L, start;
    boor = all_boor+boor_offset[k];
    degree = all_degree[k];
    knots = all_knots + offset[k];
    n_knots = offset[k+1]-offset[k];
    n_b = n_knots-degree-1;
    x = all_x[k];
    L = casadi_low(x, knots+degree, n_knots-2*degree, lookup_mode[k]);
    start = L;
    if (start>n_b-degree-1) start = n_b-degree-1;
    starts[k] = start;
    casadi_clear(boor, 2*degree+1);
    if (x>=knots[0] && x<=knots[n_knots-1]) {
      if (x==knots[1]) {
        casadi_fill(boor, degree+1, 1.0);
      } else if (x==knots[n_knots-1]) {
        boor[degree] = 1;
      } else if (knots[L+degree]==x) {
        boor[degree-1] = 1;
      } else {
        boor[degree] = 1;
      }
    }
    casadi_de_boor(x, knots+start, 2*degree+2, degree, boor);
    boor+= degree+1;
    n_iter*= degree+1;
    boor_offset[k+1] = boor_offset[k] + degree+1;
  }
  casadi_clear_casadi_int(index, n_dims);
  for (pivot=n_dims-1;pivot>=0;--pivot) {
    cumprod[pivot] = (*(all_boor+boor_offset[pivot]))*cumprod[pivot+1];
    coeff_offset[pivot] = starts[pivot]*strides[pivot]+coeff_offset[pivot+1];
  }
  for (k=0;k<n_iter;++k) {
    casadi_int pivot = 0;
    for (i=0;i<m;++i) ret[i] += c[coeff_offset[0]+i]*cumprod[0];
    index[0]++;
    {
      while (index[pivot]==boor_offset[pivot+1]-boor_offset[pivot]) {
        index[pivot] = 0;
        if (pivot==n_dims-1) break;
        index[++pivot]++;
      }
      while (pivot>0) {
        cumprod[pivot] = (*(all_boor+boor_offset[pivot]+index[pivot]))*cumprod[pivot+1];
        coeff_offset[pivot] = (starts[pivot]+index[pivot])*strides[pivot]+coeff_offset[pivot+1];
        pivot--;
      }
    }
    cumprod[0] = (*(all_boor+index[0]))*cumprod[1];
    coeff_offset[0] = (starts[0]+index[0])*m+coeff_offset[1];
  }
}

casadi_real casadi_fmax(casadi_real x, casadi_real y) {
/* Pre-c99 compatibility */
#if __STDC_VERSION__ < 199901L
  return x>y ? x : y;
#else
  return fmax(x, y);
#endif
}

void casadi_copy(const casadi_real* x, casadi_int n, casadi_real* y) {
  casadi_int i;
  if (y) {
    if (x) {
      for (i=0; i<n; ++i) *y++ = *x++;
    } else {
      for (i=0; i<n; ++i) *y++ = 0.;
    }
  }
}

static const casadi_int casadi_s0[2] = {0, 20};
static const casadi_int casadi_s1[1] = {3};
static const casadi_int casadi_s2[1] = {1};
static const casadi_int casadi_s3[1] = {0};
static const casadi_int casadi_s4[12] = {8, 1, 0, 8, 0, 1, 2, 3, 4, 5, 6, 7};
static const casadi_int casadi_s5[5] = {1, 1, 0, 1, 0};
static const casadi_int casadi_s6[10] = {6, 1, 0, 6, 0, 1, 2, 3, 4, 5};

static const casadi_real casadi_c0[20] = {0., 0., 0., 0., 2.2222222222222223e+00, 3.3333333333333330e+00, 4.4444444444444446e+00, 6.1111111111111107e+00, 7.7777777777777777e+00, 9.4444444444444446e+00, 1.1666666666666666e+01, 1.3333333333333332e+01, 1.6111111111111111e+01, 1.9444444444444443e+01, 25., 3.3333333333333336e+01, 5.5555555555555557e+01, 5.5555555555555557e+01, 5.5555555555555557e+01, 5.5555555555555557e+01};
static const casadi_real casadi_c1[16] = {1.1422408700313691e-16, -6.7192421935568869e-01, -4.3115156128862309e-01, -4.0743932473373196e-01, -3.3461584461207772e-01, -3.0119702103561768e-01, -2.5641871829839363e-01, -1.6387359326774187e-01, -2.8033209001970133e-01, 6.2801897276157717e-02, 3.9327546777981309e-01, 2.4523305778223559e-01, 3.9274760691946320e-01, 3.9403456903688200e-01, 4.8198024626463909e-01, 5.0000000000000022e-01};

/* mapping:(x)->(f) */
static int casadi_f1(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real w0, w1;
  /* #0: @0 = input[0][0] */
  w0 = arg[0] ? arg[0][0] : 0;
  /* #1: @1 = BSpline(@0) */
  casadi_clear((&w1), 1);
  CASADI_PREFIX(nd_boor_eval)((&w1),1,casadi_c0,casadi_s0,casadi_s1,casadi_s2,casadi_c1,1,(&w0),casadi_s3, iw, w);
  /* #2: output[0][0] = @1 */
  if (res[0]) res[0][0] = w1;
  return 0;
}

/* mapping:(x)->(f) */
static int casadi_f2(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real w0, w1;
  /* #0: @0 = input[0][0] */
  w0 = arg[0] ? arg[0][0] : 0;
  /* #1: @1 = BSpline(@0) */
  casadi_clear((&w1), 1);
  CASADI_PREFIX(nd_boor_eval)((&w1),1,casadi_c0,casadi_s0,casadi_s1,casadi_s2,casadi_c1,1,(&w0),casadi_s3, iw, w);
  /* #2: output[0][0] = @1 */
  if (res[0]) res[0][0] = w1;
  return 0;
}

/* Path_parametric_MPC_expl_ode_fun:(i0[8],i1,i2[6])->(o0[8]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_int i;
  casadi_real **res1=res+1, *rr;
  const casadi_real **arg1=arg+3, *cs;
  casadi_real w0, w1, w2, w3, w4, w5, w6, w7, w8, w9, w10, w11, w12, w13, w14, w15, w16, *w17=w+29;
  /* #0: @0 = input[2][5] */
  w0 = arg[2] ? arg[2][5] : 0;
  /* #1: @1 = input[0][3] */
  w1 = arg[0] ? arg[0][3] : 0;
  /* #2: @2 = input[0][2] */
  w2 = arg[0] ? arg[0][2] : 0;
  /* #3: @3 = cos(@2) */
  w3 = cos( w2 );
  /* #4: @3 = (@1*@3) */
  w3  = (w1*w3);
  /* #5: @4 = input[0][4] */
  w4 = arg[0] ? arg[0][4] : 0;
  /* #6: @5 = sin(@2) */
  w5 = sin( w2 );
  /* #7: @5 = (@4*@5) */
  w5  = (w4*w5);
  /* #8: @3 = (@3-@5) */
  w3 -= w5;
  /* #9: @5 = sin(@2) */
  w5 = sin( w2 );
  /* #10: @5 = (@1*@5) */
  w5  = (w1*w5);
  /* #11: @2 = cos(@2) */
  w2 = cos( w2 );
  /* #12: @2 = (@4*@2) */
  w2  = (w4*w2);
  /* #13: @5 = (@5+@2) */
  w5 += w2;
  /* #14: @2 = input[0][5] */
  w2 = arg[0] ? arg[0][5] : 0;
  /* #15: @6 = input[0][7] */
  w6 = arg[0] ? arg[0][7] : 0;
  /* #16: @7 = 0.36875 */
  w7 = 3.6875000000000002e-01;
  /* #17: @6 = (@6/@7) */
  w6 /= w7;
  /* #18: @7 = 73.457 */
  w7 = 7.3456974659287212e+01;
  /* #19: @6 = (@6-@7) */
  w6 -= w7;
  /* #20: @7 = input[0][6] */
  w7 = arg[0] ? arg[0][6] : 0;
  /* #21: @8 = mapping(@1) */
  arg1[0]=(&w1);
  res1[0]=(&w8);
  if (casadi_f1(arg1, res1, iw, w, 0)) return 1;
  /* #22: @8 = (@7*@8) */
  w8  = (w7*w8);
  /* #23: @9 = cos(@8) */
  w9 = cos( w8 );
  /* #24: @9 = (@6*@9) */
  w9  = (w6*w9);
  /* #25: @10 = 9032.92 */
  w10 = 9.0329197556223498e+03;
  /* #26: @11 = 1.45027 */
  w11 = 1.4502715506375901e+00;
  /* #27: @12 = 13.1632 */
  w12 = 1.3163204541541001e+01;
  /* #28: @13 = 0.985 */
  w13 = 9.8499999999999999e-01;
  /* #29: @13 = (@13*@2) */
  w13 *= w2;
  /* #30: @13 = (@4+@13) */
  w13  = (w4+w13);
  /* #31: @14 = 0.1 */
  w14 = 1.0000000000000001e-01;
  /* #32: @14 = fmax(@1,@14) */
  w14  = casadi_fmax(w1,w14);
  /* #33: @13 = atan2(@13,@14) */
  w13  = atan2(w13,w14);
  /* #34: @13 = (@7-@13) */
  w13  = (w7-w13);
  /* #35: @12 = (@12*@13) */
  w12 *= w13;
  /* #36: @12 = atan(@12) */
  w12 = atan( w12 );
  /* #37: @11 = (@11*@12) */
  w11 *= w12;
  /* #38: @11 = sin(@11) */
  w11 = sin( w11 );
  /* #39: @10 = (@10*@11) */
  w10 *= w11;
  /* #40: @11 = sin(@7) */
  w11 = sin( w7 );
  /* #41: @11 = (@10*@11) */
  w11  = (w10*w11);
  /* #42: @9 = (@9-@11) */
  w9 -= w11;
  /* #43: @11 = 9326.44 */
  w11 = 9.3264444714682304e+03;
  /* #44: @12 = 1.44323 */
  w12 = 1.4432305676742601e+00;
  /* #45: @13 = 15.0694 */
  w13 = 1.5069384157767599e+01;
  /* #46: @15 = mapping(@1) */
  arg1[0]=(&w1);
  res1[0]=(&w15);
  if (casadi_f2(arg1, res1, iw, w, 0)) return 1;
  /* #47: @15 = (@7*@15) */
  w15  = (w7*w15);
  /* #48: @16 = 1.97 */
  w16 = 1.9700000000000000e+00;
  /* #49: @16 = (@16*@2) */
  w16 *= w2;
  /* #50: @16 = (@4-@16) */
  w16  = (w4-w16);
  /* #51: @16 = atan2(@16,@14) */
  w16  = atan2(w16,w14);
  /* #52: @15 = (@15-@16) */
  w15 -= w16;
  /* #53: @13 = (@13*@15) */
  w13 *= w15;
  /* #54: @13 = atan(@13) */
  w13 = atan( w13 );
  /* #55: @12 = (@12*@13) */
  w12 *= w13;
  /* #56: @12 = sin(@12) */
  w12 = sin( w12 );
  /* #57: @11 = (@11*@12) */
  w11 *= w12;
  /* #58: @12 = sin(@8) */
  w12 = sin( w8 );
  /* #59: @12 = (@11*@12) */
  w12  = (w11*w12);
  /* #60: @9 = (@9-@12) */
  w9 -= w12;
  /* #61: @12 = 2283.36 */
  w12 = 2.2833600000000001e+03;
  /* #62: @9 = (@9/@12) */
  w9 /= w12;
  /* #63: @4 = (@4*@2) */
  w4 *= w2;
  /* #64: @9 = (@9+@4) */
  w9 += w4;
  /* #65: @4 = cos(@7) */
  w4 = cos( w7 );
  /* #66: @4 = (@10*@4) */
  w4  = (w10*w4);
  /* #67: @12 = sin(@8) */
  w12 = sin( w8 );
  /* #68: @12 = (@6*@12) */
  w12  = (w6*w12);
  /* #69: @4 = (@4+@12) */
  w4 += w12;
  /* #70: @12 = cos(@8) */
  w12 = cos( w8 );
  /* #71: @12 = (@11*@12) */
  w12  = (w11*w12);
  /* #72: @4 = (@4+@12) */
  w4 += w12;
  /* #73: @12 = 2283.36 */
  w12 = 2.2833600000000001e+03;
  /* #74: @4 = (@4/@12) */
  w4 /= w12;
  /* #75: @1 = (@1*@2) */
  w1 *= w2;
  /* #76: @4 = (@4-@1) */
  w4 -= w1;
  /* #77: @1 = 0.985 */
  w1 = 9.8499999999999999e-01;
  /* #78: @1 = (@1*@10) */
  w1 *= w10;
  /* #79: @7 = cos(@7) */
  w7 = cos( w7 );
  /* #80: @1 = (@1*@7) */
  w1 *= w7;
  /* #81: @7 = 1.97 */
  w7 = 1.9700000000000000e+00;
  /* #82: @7 = (@7*@6) */
  w7 *= w6;
  /* #83: @6 = sin(@8) */
  w6 = sin( w8 );
  /* #84: @7 = (@7*@6) */
  w7 *= w6;
  /* #85: @1 = (@1-@7) */
  w1 -= w7;
  /* #86: @7 = 1.97 */
  w7 = 1.9700000000000000e+00;
  /* #87: @7 = (@7*@11) */
  w7 *= w11;
  /* #88: @8 = cos(@8) */
  w8 = cos( w8 );
  /* #89: @7 = (@7*@8) */
  w7 *= w8;
  /* #90: @1 = (@1-@7) */
  w1 -= w7;
  /* #91: @7 = 4650 */
  w7 = 4650.;
  /* #92: @1 = (@1/@7) */
  w1 /= w7;
  /* #93: @7 = input[1][0] */
  w7 = arg[1] ? arg[1][0] : 0;
  /* #94: @8 = 0 */
  w8 = 0.;
  /* #95: @17 = vertcat(@3, @5, @2, @9, @4, @1, @7, @8) */
  rr=w17;
  *rr++ = w3;
  *rr++ = w5;
  *rr++ = w2;
  *rr++ = w9;
  *rr++ = w4;
  *rr++ = w1;
  *rr++ = w7;
  *rr++ = w8;
  /* #96: @17 = (@0*@17) */
  for (i=0, rr=w17, cs=w17; i<8; ++i) (*rr++)  = (w0*(*cs++));
  /* #97: output[0][0] = @17 */
  casadi_copy(w17, 8, res[0]);
  return 0;
}

CASADI_SYMBOL_EXPORT int Path_parametric_MPC_expl_ode_fun(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int Path_parametric_MPC_expl_ode_fun_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int Path_parametric_MPC_expl_ode_fun_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void Path_parametric_MPC_expl_ode_fun_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int Path_parametric_MPC_expl_ode_fun_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void Path_parametric_MPC_expl_ode_fun_release(int mem) {
}

CASADI_SYMBOL_EXPORT void Path_parametric_MPC_expl_ode_fun_incref(void) {
}

CASADI_SYMBOL_EXPORT void Path_parametric_MPC_expl_ode_fun_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int Path_parametric_MPC_expl_ode_fun_n_in(void) { return 3;}

CASADI_SYMBOL_EXPORT casadi_int Path_parametric_MPC_expl_ode_fun_n_out(void) { return 1;}

CASADI_SYMBOL_EXPORT casadi_real Path_parametric_MPC_expl_ode_fun_default_in(casadi_int i) {
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* Path_parametric_MPC_expl_ode_fun_name_in(casadi_int i) {
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* Path_parametric_MPC_expl_ode_fun_name_out(casadi_int i) {
  switch (i) {
    case 0: return "o0";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* Path_parametric_MPC_expl_ode_fun_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s4;
    case 1: return casadi_s5;
    case 2: return casadi_s6;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* Path_parametric_MPC_expl_ode_fun_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s4;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int Path_parametric_MPC_expl_ode_fun_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 11;
  if (sz_res) *sz_res = 4;
  if (sz_iw) *sz_iw = 8;
  if (sz_w) *sz_w = 37;
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
